apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:H/LPnJhMaWZ2y4pr50SlNqdhavI/IIw1sJWVlsdWWPS8jZ2sD2LFmg==,iv:Byv1PNA8iCs95Wu1vogu4D4nd7NV+6NwjxgPFwudVnk=,tag:BqNNll4dksU/w++LIP/luQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dpafzlyh6kar7u02x56k2g83tmg2g3t8aglwzupku8z639gqx5hsvts92d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnVEVjWmdiRUxJcmF2MXBV
            SHlKZUVGd1JCMmdTb3FRcEpGa3JFNEpueTA4ClNCZmRoNWxkZnJFcUJ5OXhwRlVJ
            Zkt6TWNXSnNlSjZFaElLU3l6ZGw2WXcKLS0tIForWGk4OWRmMGkrYnBEOFduRzdD
            QTNvR080VEVFSlZkcEtDQU5YMFA1RTAK1AmmY2dntG7CdHf7ssmH6APKsADLaFy8
            BUYqJp5Bk/vEjlaKZvKXcqHGcaOyXljBIcPH5JVjtLuYYLxbXOYoFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-12T07:13:28Z"
    mac: ENC[AES256_GCM,data:5N+ki+qGIry18ssbDTaakMi+ftQTZVciMH6lJMTu9DXS326OGpsH8nonpNlRxaW+nTdfrKekEM2VQGkV/FzxJN9i8tMbC3dc4JJbxra2Pw6ixUyrRbl4n7PHLnHfxE5E5aolEyuzKZmatkBjyQv6hgvQMlKjJyD1y7vxhVGX8CY=,iv:o4/4jJp+gYMbA8+uAVUQxcU1EsByXD+z1w1TRgxT3hY=,tag:SfwAhWHcpnJMQkTxSgRsdQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
