apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:Fnv0vQxsEt+4m79Gpu2COkC4B+pK4MwkBUutea6+LXq1T+h8ZJE2Gg==,iv:UEXik7QFkOTibrsMa5AXxljD9fFjIfUI07qUMUhKdzc=,tag:1DYOsFhU/i81IthZGemVEQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dpafzlyh6kar7u02x56k2g83tmg2g3t8aglwzupku8z639gqx5hsvts92d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzVi8vL2p1ZE5nM1BKR1Ur
            aFc3ODJMTlZiWmRRQjduTEV4VVYxQ0UxVFRzCmVZenU0QTh2U3Uwa1lmTGNYekYz
            MmRjNlc2QW9CYzEvREd4MGdkNjNMK0kKLS0tIFpGbUFId2pmSkc4L2Zhc1dKNVlO
            Sm9vQzlQQ1RxWGdCUHZ4dS9ENVpHcVEKTKTDCCGRG6pY/5hFWD6jdEabSBivW3l2
            nJ9CvJbO5VP65h4SYUPMkmTG6b20JELmzWOkY2u500vqqoiz+X6rTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-05T10:18:05Z"
    mac: ENC[AES256_GCM,data:97NKQ/tOf2RxV4imZsUjlMf3sUN3lcnzFmV18hXJB0WJdC+vUnqiA1SkKkki4ivUcyZcpPKNV6K/Rh/zrx05FGBK3v3AB8P6ts1FIf1qCQ+deZ9ZB9AmOvpcCafig+cl57Q1XYzO8k+3vIt0fIIxaPAY/xmgSAOTLKEdcsvM39A=,iv:CqTHgaWpHQkql26A5a4vKcJ8eKuwxGaSsaaFolqPgAs=,tag:hvAnofvYC5ZaUQJOtycoFQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
