apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:xlKdksnJeY39KpgnQ7f2Vr5cDteAYcoqe4uoJ1OeEBVZ78Qd2hREOw==,iv:VvNKusDT0Whcn+HbeZj6AbQPldwN489I1HRVLXj66GM=,tag:8Giswme4v4YpNXEYXoT1WA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dpafzlyh6kar7u02x56k2g83tmg2g3t8aglwzupku8z639gqx5hsvts92d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEM2xySGEwZ3RKRUhkSkI3
            L2dQVEJvWEJwWlRZUlE2TnJPb3VGYzVBVVNvCjFKMUZZMTJlZHRqUVB4Z0s2Rjds
            UU1TR2tsRnJqNHk5aFJZNEF5SUEwQ1UKLS0tICsvN3YvNG1EdnVvaE1MMlZCV2k2
            ZHM0bnRmSlpCdHM4VW5LQzc2M0JrdFkK1lB5kRQxxAlf51omBcevwlnrKa+Tj7OD
            XnS84K6hr2Rqex9kWotE73CBH+NPJtTP/XictXLEToXMvP+CmXfGJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-17T14:38:26Z"
    mac: ENC[AES256_GCM,data:YPZJrgfVwlCYSHk3Pr588r1OQuOnGNh8rvEHIR72FJo0CvM8c3RTa0SNj0AlSEL7DyS6njRSwprIRuC8YYENUgsDhox/Va8Ul+Kn+zo212PYkrPGLAZE7bV9oxBjT7hFpJlIGulTdTXZXKZTOhcd/Vkqcrq21qpQ4uk/mZBWpVI=,iv:TbGCpq3b8pQEU0qaqjLmLX7FRmsfvNotDqjRC6InTVY=,tag:fd+yUyStYTmX7muo/g5B9A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
