apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:M03Bj5saDkPf34QQE2GoVo8I3lh/HVtqNU3zoQ0KDQANn5w5iR7KeA==,iv:CMlwyYvw/sO4mixV9ySSkLCy7s+yqx1lo0b8B7BEQq0=,tag:5820Yv+49J8jr6LLsfvctQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dpafzlyh6kar7u02x56k2g83tmg2g3t8aglwzupku8z639gqx5hsvts92d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZU44MEtYcFB1aWRWSU9S
            N0Z5amFIdHV5ZktUK0tQMTFWc25wUm9acXpJCnhTOXN5ZzBLQ2VTSGs5MWU5MnY0
            dVhRS2p1RG95TCtJdzlPUy82QnN6Vk0KLS0tIHJaNDRUY08xbTJYQllsM05mKy9s
            S0pUNDg1M0o4ZHl2ckRvUkFPeDAyVUUKeLefujFRZ4RK5eAsoyql13yuQDXU1x6t
            ICE/qShGXmpPxHn2UWTF7C+3JO9K2r4XfOsBVF31FP5b6Oui+Crqvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T10:15:33Z"
    mac: ENC[AES256_GCM,data:/jwv1+okJ96919HwKQ4IxamRRXFD+tXRDk+wvpEI031L/an4F0J1yQHBl41IJI77hWf4OTZhOjJ054kEbvLz3mdYqFQKfE2ma+0cY+VqIqcaFmqa2+gtfpigi7cPVSfgOS1CK6lO254jSp2ilKvlbA4ChpdHWTWBGl6IE6iTzmc=,iv:AzYd0RR/5BsGKWXn4WitzpG2SSoSSqHhtXTQsGwIVsA=,tag:KCOg7+gwoV7ydsjx0eBi+g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
