apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:eDrfXYZLynpMgr1FBaLI2yuxbKVVAMBwyodRrOuz0ocBU+m15Glh6g==,iv:ChnW0H0zoHB1QVFid21uNsU/nIrRZkKdpAeH2nzs3JI=,tag:L/qh3puu0Ef4pzobGYsGBA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dpafzlyh6kar7u02x56k2g83tmg2g3t8aglwzupku8z639gqx5hsvts92d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNZ2hsbTF1NzZvWTVoMXI1
            dGlPZGgwWEgrdms4R3pzRGZFQVdMY2l1MVFrCkdhZWZUano4QmFyLzZLQ2FicnNN
            ajlRVGFQRTBrOVhINWVETVBkL1QyUlkKLS0tIHdIc0NNTVcxeXJvMkR2OXV5SkZt
            M0RlTHdZZUpzZ3NIaWpnZmpwbDByTlEK08jsJXYXgHPOs3WIbeEJXxSMHhOnW3E3
            BLHBrgnezckMTD8DGtpIxfI0Nj4nTNs+UKoemd9Y0G6jrbch3oxdKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-03T19:02:51Z"
    mac: ENC[AES256_GCM,data:4qd58Up2BQwlkL5+DZVZaNmj1zyTbW6PQFaEW/nSKvVxSojFMvjSTcxOxho83g/CS1iaS06pFKWz7c2AZNrfieqMiu4Uag0B6bGlhY4Hv1WLDDjquJYrv36/wjTX1sAO3ZBL5GFJO1V4JfLBjBS/Ji9Bbb1C3dHEAYa6UGIW6uo=,iv:V3ZqwiUC2rIEBPpFkIf7yvdJ80/G1oeQwjOjYkAJyC0=,tag:aJveAgOt9hhrkKvx8Fjk7g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
