apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:obRAEJsMvuf6okfq5k0b80NFs5N9mE8O4ItJGzQUo5ItogG52m1IWQ==,iv:sgNcYIRE2+DWWfdfogxbnICCxSV2CIvuZAsvl6fnvv0=,tag:aNrWdvffLMNU3hEcg3YITQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dpafzlyh6kar7u02x56k2g83tmg2g3t8aglwzupku8z639gqx5hsvts92d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpeUtBdGF0dnhjb1Rpenk1
            ZG43Mk5SUWxpZmhXcC9oNmg0dWtBRDV0MWpVCkpnc1daR21HRk5vN0srZFVkREVD
            KzBkY0dHQ3QvS24zM2VTU05ibTRldTQKLS0tIDlicXBELzB2cDlFVktnN2MxM1g5
            REM3Umo4cEo5UUE5WWF4cUtOQkZ2WnMKOLHg8uYg2olUQ6eZAs0YIlkSEoEotSmD
            pezUTXq15bppwwiPkKaRmzt+lxGNQEviuVKV2jhNef3ndQC4zjoGNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-13T05:21:22Z"
    mac: ENC[AES256_GCM,data:+DlH2t6+talple+RbAMBeza4zUnClwmkhg3vL1yPvqXy3PKDZkbjPeOHBtVx7YgszNmfB0RVqHsIstrnxe1aFNp0hD2z3XqWH3D3N88lx137WtMx/9j2sqQa542q7Ws9ekBFzKrGcqGxRWynNuhQg5g3EUDqagpXuujhLPQvv+4=,iv:k0nDw4adADvGizE4khvCX0DoUuT4yZlzaQG3+I/GKCA=,tag:o6Yo/R9JjQtWz6uFyy9QcQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
