apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:TonUfzLCE+fXI3zic2isQrgZRh4LZ3qlIlFbVr5zKZis2n8wNLjPbQ==,iv:SXOK+RGE1yJlSq6MZ/6Rs0pYNSSAEnz7jFdFWeL2n44=,tag:7BjiBTYrqygomG8c1nTT+A==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dpafzlyh6kar7u02x56k2g83tmg2g3t8aglwzupku8z639gqx5hsvts92d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwdjQrVnBmV2hVSTlQd2dk
            UnVzcTd5MklTVVE2S0pucDFXNE1reFlhOFU0CnRUQi95NjVVWXhjTWw3aUc5cmdj
            SWw5TGhFUTNsNWhvVVVsREFvbXRlQlUKLS0tIERzZlAxalBSdCtPT1l2dnphNHVY
            cjN3QlFOeXFvNG9wMmhxNEljZkNiZjQKX5ZaeHADzWQh+gQIDnoiGYDWTDpfleUU
            zrc8HnxIOqL93vvJGd05BhZ84oTRS7TfolsQq4wayznXsmiJXDDv+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-03T17:27:57Z"
    mac: ENC[AES256_GCM,data:cIWg94ghYxJwGVnxw55Lpa9TE/aRsiCEnmt+RmVuQyV0B1AFkzTZYPUUy0uZX3ul/50dimw3FkuZ+fM8zs9egEEGqJXV0GSsILmCl+34O/vCbvorSAQH3H3ASiGfndxh6+CC1GLPsE8b+TCWmCU+f4Fq0oHtsxe3uBvTvOfRKqw=,iv:V66oklcMeMZ8yQF3KzqDQ/arJ1ajk4k4lZAxbx3JXbk=,tag:J90PrTWLgakp5WwSJDMz4g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
