apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:TZ1yuTnq+WzElIyLF9E1ppHAm+kSEnnqIzpmSoQTJdUQSyD8Lk7Ztw==,iv:Gn8HINAqOkrV/Re0uiUoyVVFTgfgA7WCqs6wolZNMqc=,tag:7+eM4oPrjQPpww7erhSvnw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dpafzlyh6kar7u02x56k2g83tmg2g3t8aglwzupku8z639gqx5hsvts92d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArVk1FdHJaS0VSSkhGT0ZQ
            L0NTUjUzS0REeG5hdk5vWE5FdmdnL3RKTWtnCnkyWEYzbG1HeEoyR2Q4VFI4QjQz
            UUtwOHYvL2tWZzNkb25XUkN6V0pTN2sKLS0tIGpldWhvZnJRblJzYjdrVmd6cVJL
            bGh1U2J5NmcyL3A0V2lSVFltb3hBYVkKWk99K/W45z7sP8Z96YEqsMMMRwF6j7Cm
            fS+wM57Gtuk9Y4ehA9Brbq7y+ZR6udmMdMnW/DAusbFp/kFvWjcheQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T09:00:15Z"
    mac: ENC[AES256_GCM,data:zTc1v8unyXR1eec45aBBcTHkn75AG9SV31Mptbn93LdbXh8GV4ExK52bfyaMPX+2FXc2lU66GT3XPORog4yo9AkbOpFaRR3mhEZgxk1PRKNjSAFL+XV+ZNs3WTwYLiMZkFGRV6lUua1l0IfOv5yBAjppgz0PgVlngNbwVaR33yk=,iv:HqPpavJ0JOpadUOOrqQ5Ectlrr4kMoqHlykULwWv2ng=,tag:+n8/AdwJatJU9hpyBTJD+Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
