apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:XP1gLOq38vKIEgw0d7R1q6XV7tUyNIHBY5TDaYUwNRKmassfiRev4A==,iv:HQbqONHUdqKycu6s7b10N199FP3lW5PvzGX0DFJP54Q=,tag:J0jBElPvGiKSKwGPIDrTlA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dpafzlyh6kar7u02x56k2g83tmg2g3t8aglwzupku8z639gqx5hsvts92d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVzdTZHVMVm8xdFBVUjhV
            RExRTVZNS0pUWHZxNmRmdk9zdk03VXYySmhzCnRnL0JFa1RWYmV0UkNmU2ZEY3Vn
            VFdhaHB5M3FjRzB3UVRDQWRsZWN3THcKLS0tIC9rMFNmdEg3RjBEOHdLOVh5YjdC
            cXdUQjRMRTVlamVxTjVKNXY4K1cwQncKx0hyFJeg21J1sDUhKK4euO8epVhqEMBe
            oCw/EdDTEHRBN500jfsCrpombNp9Ojt9WPgDw2gZOH2D70fekXX7cQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-19T17:46:45Z"
    mac: ENC[AES256_GCM,data:DTucXRWvez6NnPzH7G8oNKB/GqdTpPxTX6g3efHQswgTMaWOLcb/IclMeckNJrkaOXNTPpZ6XzMb6BTuQaUAw0zr4m52vJyayAQBUxTCbAIwDINy4CYsJa42h24qsIPlLwwXct1ET6eiML87X3C2LmAWAS0cZ5gVHxkDSVwUytQ=,iv:RgL5hY2F5d7FO03aigTVAyK23s50IyD7Ne9ZSxQJzwM=,tag:EiqX0sof/NfCISsBYyGcLA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
