apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:RQMBK3ZAHQwKwvo0CZ5xzhzXxiGRRMW9FsNiHyHXoACfh64UqVtKhw==,iv:Y4SFkfca16sm6X4x7r20jdoeKhD4AJwNzggtfYAYfRI=,tag:oOUt+RuU3oFhaQPOL2Xhvw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dpafzlyh6kar7u02x56k2g83tmg2g3t8aglwzupku8z639gqx5hsvts92d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArL2RrMTlST2xkUWxnRlFO
            RVBXYjlvNnBXeGxtTkNxNkRtbUg0Q256NG5NCnFBYTZMRFJyMjRSWU95aC9NakpN
            RHBFWW0rNnhybmVxUWg3VEgxMURpTEkKLS0tIHFxTERicFIzK29ZT0ZhbXJpcW9B
            ZzgrVllQNU1mOU9aZzVyS1FpY2R0d0kKcccZcEKzotZSymfv5PxYwrD2coLz74kr
            lAR4/o+B2K2H1FPCYO0Zhi4KFh+GtvD3yuL4Q8eig6mBMH4UomIt+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T16:30:29Z"
    mac: ENC[AES256_GCM,data:2RU7GXFAnIO7pEJo5IBVxJx0pVMOvaB3UK2FipoDPRWpfc1OXZyP5rUUTV5ZF606yilindZOcomSbqDo+WnZgzYr4QIh3BssQ+9SddyHoiL8j5YWNJA4YmU3PFebqMta4QH8wV6t921xIWVR2UeXjXqg/HO3mT9/Pwt9nAH2rVA=,iv:FDGOW69Kc4wvII3bBOdUCYm9x/0FBKT6dI9Cdcd+Zxc=,tag:eSdmq6W0OH+nFAIuBBsHFw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
