apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:PedMrOauO+IdSTWn0pkLyEjvK5e7ES/sWYzxsxl2GMGw4w/dU08gXg==,iv:l0XeULynuITZBe1J2x3BneWQUA5WuCr7vEvf/JEsB80=,tag:WICDk3DZybbO4dNUj6DkQQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dpafzlyh6kar7u02x56k2g83tmg2g3t8aglwzupku8z639gqx5hsvts92d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1RjhER0pOWmVkTjJiRm5F
            alJoSmxvd0VUVnBYUjBVbmVnVWk2Z0M1VlY0CjZMejVPeXArWFNrVForNXVDYk9l
            T1pXNW5ML2JldEN4WmtoanZPWUNVWVUKLS0tICsvUmQxRzZyWGJWbzdvbUFtSmpE
            akZ0b01xOHdmUGY4QVk4bSt3UFg2WTAKJ1JoCnSel6CtV83g9dJDTuyZwbuh6vUP
            gOPlhcFKsWoVqU0GzgtQb/+LOV265Y8N5NHDHr0uqTRmnCdXQAkmLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T07:47:25Z"
    mac: ENC[AES256_GCM,data:2DcoeXm8MGrQa0obbecQwEmEub+1H9/i56w9IIkEp1Mnc49Ip5YRrDgonbbFNghqj7aYAAegu6jQ+U8PhgcqkNuvy5Q/+UWGpvudkfnE9CazDCPlD+wmcP79TyAJX5noFMwcHKZK8Z+WHyUR1E+exB/2Cad7P6nOsLaAPJPf0BM=,iv:5Eu3fSSpwPMrykVx60ITZ/x1wGFlxNddDDATkPTSJkk=,tag:qlgNIIYqJi2FySkIpcJl7A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
