apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:0xhcs0EDV8gvT14OKInhYvyoBxfgIbNcoPpZsMu0grlPMd2TmzPbrw==,iv:2d5m57lBmdH0nU8gZ0E1wBBYUZGQNqqaJsZFKU+G0so=,tag:LvZTQG34LUVyD92uDDE1SA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dpafzlyh6kar7u02x56k2g83tmg2g3t8aglwzupku8z639gqx5hsvts92d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1UjcxbXNnOUJvcVd2RndQ
            WHBRK1V5bWFTS29DdjZxR1dMQVFLR3Rqa204Ckh1N1lmZmhla1FSRitEUlRWaENO
            N2tpMWl6U0RmdTZreGdPNTZyTmpqZ3cKLS0tIERyNzdvWVg2U2ZhTCtzTFM2UThY
            T0lnZHdvMU1sNVF2M2xrVndSY2FRZTQKizUIVnLpHh3RZmu7J/pbVpnQsJneWAGJ
            FwEqggrzuEnO0RJN4S4/Jdanwtq4Tu3dNao6IqQuuXXbLr1ZNsnw/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-03T05:49:06Z"
    mac: ENC[AES256_GCM,data:3kjBm1OyLM5lK/9WSqHQfn/P5FES7DUrDI9LGOxFDi2czQQQoWFdiamb2W4OI+pEVWEfPulY3W1XQGKRF17GOlZJ1Y2hdugGRswaMMi4oUYmsi1tA9euvWQyPKixxL36qyNb7jym6jlegAwesJfn34wBe1L2nVaF/Am1yoLvN+c=,iv:oikbqMw56uisCOTnOBp/SgbFFfOwxY2SoqPmFSWemGk=,tag:vKDoy03RDMfRbOfCSV5wwg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
