apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:sLRBGwdxyDp/AZEHQwIWr4wtsD291vkLHkhWhlcWWUtNM0IzlJ0M4w==,iv:DkVPehe/7g1VjwZhQUhg7RCIzKugqXBegfmyOosZcvY=,tag:vzKDAVVKauU7MDdwSLOSTQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dpafzlyh6kar7u02x56k2g83tmg2g3t8aglwzupku8z639gqx5hsvts92d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVSVljMmplRmZBQnFUZGtH
            N2FKUjFPemFwajBtbHBlQWRkRjFjWStXQXpBCkpUcTlIWlVHeUVlMEVTVHUxcHVH
            eG1WUjBKODVXaTNEK3YwZTRZVDJwdFUKLS0tIFBlY003NzBRTElJUElqNi9JT1F2
            em42S1ZsSWdYL3lvbGtuVTAyN2FmR2cKP2mMia4P/+5JkGrkaSBhSMopK7b8IAuS
            c2YHezyQUR1taoa+oM58hTskcsB3/mfHpl1XGnEpry6uqTfWEQm6Dw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-19T04:32:36Z"
    mac: ENC[AES256_GCM,data:ATrKR6TnDzTBB1IzvGHljxakcL1uXKmiLOJZ3RUoagPwkHtPp+ufpszVcW3QPgwOYzu7QuNvJZqWz7csn6JD9k7jcydqdObUoUjpdZ8UWh4tIiVn9lnPGwl6D4RpbVUiZy+JVmh6BlYpSUwYXLhhFtUjflKb+4Iu4l9OwEgeVPk=,iv:WWy1+dvAlDNDLn6HHxiFERzp0V/Q9jLO3NC/RJzwogQ=,tag:Dn7fcTT8svnP33eM2GwOhg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
