apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:zN5hG61TG6nJmgE+TKXJaOBmWbd8gb1fEVWP55bXkDDKBeC1or9ing==,iv:D83Q3bP2vqNA3Hf5JS7/Dp652MzH/gs0OCX2gJwGmpE=,tag:IL0W1dCTVDuNDP8Ry04y7Q==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dpafzlyh6kar7u02x56k2g83tmg2g3t8aglwzupku8z639gqx5hsvts92d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvVTdyckpJZktzY1NSd1pG
            NUdwLzNGTG12YXJwdUpFOVJIS1lhOHRMa0MwCkhrR0lBdEJ2YzFscTNRR0NvNDJE
            dFVsd3BtM3I1Q0F3c2lHN2pxNzZVYjgKLS0tIEYwMHd3UG1xNHlpeExEMjBncG9S
            aldwRlFNQXpzdWFHYWVqZk5RS0ltY0UKvlFo7zPoYqcjOEiyda8Md0TayRu12pNg
            UoxKbE3tQVICr6kaxzjwxtqIKHVR8Zd0KKu5lHlW0fWX8qApV2yyHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-23T09:19:39Z"
    mac: ENC[AES256_GCM,data:PekazkCWW8tHaaQd9gMJ/NQ9DWXLekupaWL5Kvqyc0rr0zG7qzvZtW0tIVPRUucsfknQDmpAxaQc+AqKAdELianCcquc5APdawIDpqy9yCaby5+lqmf6b52Yhfq5ZXljXAlbCTcwS+tCBwKXJeTNUOsW7/9UJDaud2b7K/XHV9Y=,iv:kO4wq2yAQg1dRPd/2p+VxlQ6/64XJU/MNl9XSwaUlwo=,tag:+0QjhncmFpirDpQ9NpwQvg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
