apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:py8DzVro52aWQIO1SmVYxNcsN3l7hr04aALFbJke/nJHAT+HTeSVOg==,iv:KoHyzgRsQo0a3ELsQEeQfO5jpf+fnrxQ30AkLab9HfY=,tag:kvU21QztgiM/lBwIuJxb1g==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dpafzlyh6kar7u02x56k2g83tmg2g3t8aglwzupku8z639gqx5hsvts92d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5VkZ2bVJaaUVQQnc0TVha
            NXVhd09lOGlKU1ZOMHhuV0c1T1pMbFpXZVZJCmIyZmVBT2J4aVhZQ2ZDL0M3M0hC
            djVYQk5MV2RrRnNkWUVEakVGRDJDR2MKLS0tIExmNkl2M2wydlg4V2RoR0RML2Vu
            KzRBZkdDU1hQTXNobjBKcGhFZ2w0NzAK9D9/s9sxEIW7uMVuwi9IVFGaXXcsqn47
            WkBwdNpuX4AdgWbWzX/MGpG+YE7K8r2tg7zELfkpdef3HHmAhPQxCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T09:30:16Z"
    mac: ENC[AES256_GCM,data:AdTqdYBSPfiAhRC0mJ4xyLzfrZaO69+mzLwbWMAJjz2JTUaFyiOJw94qZwKNNJkSk4V4Ewr2IL2x78UczRKDte3nU8X1xTiQU/Vp4kjA1E9GHGcnRuLC8iRXm8N0pB8OxPJQ6wMF3OmK572pzAEgVxuFhyPnkeiv5EDd39MlENY=,iv:fqWgxHa1f9tmZGgoPjT6ZyhRA01x9RrQH2V9pGKruxE=,tag:ruhrGuMuCzsLNtyALpEjKw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
