apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:iioYKWEY4dtlNoOzYiSBPzwb3qbmIj+p7oNPPg5D9CXcypFuCmpiEQ==,iv:QlpP3cZ/+BIygghWr8J2wNLuaVjjlWLVkxuy7PdLVQE=,tag:2z9ZZmgrSv9NyVv10jvJ2A==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dpafzlyh6kar7u02x56k2g83tmg2g3t8aglwzupku8z639gqx5hsvts92d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkVytnbm5wYjR2a1RqaFpu
            azRWZDVBTXdjcElmV2dJRVl0Uy9xV1JKZFRZCmZVTDNuUDVJRllnRlZHRmdZT1A2
            TXpPR2NndDFqMkFMMUVCT3VBOER6OVkKLS0tIFhGN2lhUHhlZWtyRzRYZTYxTTBs
            dmowNXZJUU9LSSs5cUlJNHhoMFFwWDAKwqYpSVoE9ssM9w0txnj8CRwibBmVLcUL
            gd8WXaIUsseeHmuKOWJCGppWGaBGDAFY22azh/tAybB18AdXFPyO5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T10:06:57Z"
    mac: ENC[AES256_GCM,data:p9hVJRScWyxbmq5e4Z0LZOPIk2Licagd0AL1oU3unlKMdrcL5wHha9RJwV9w0AbQTec1pMweog9qc51lhuEglBYhOCuDPFMJ0FuqGrdn8hhuOVKSCuW+BxQULEKwB9ECBdkzRYPZsDlpypwc0hFDEcOeDmr8On4R9rgiLdlqs3k=,iv:VdgKx27BSMdw1E7jo9VFE+JYOhtDXDB7A2ydllfW8VY=,tag:tZqAyvkn71ncZUUl+AvTlA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
