---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: enshrouded
  namespace: enshrouded
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 15.29.18
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: ${TIMEZONE}

    image:
      repository: mornedhels/enshrouded-server
      pullPolicy: IfNotPresent
      tag: 1.7.1

    service:
      main:
        type: LoadBalancer
        loadBalancerIP: 192.168.1.59
        ports:
          main:
            protocol: udp
            port: 15637

    persistence:
      game:
        enabled: true
        mountPath: /opt/enshrouded

    workload:
      main:
        podSpec:
          containers:
            main:
              env: 
                PUID: 568
                PGID: 568
                SERVER_NAME: Lunarch
                SERVER_ROLE_0_NAME: Admins
                SERVER_ROLE_0_PASSWORD: secret1
                SERVER_ROLE_0_CAN_KICK_BAN: true
                SERVER_ROLE_0_CAN_ACCESS_INVENTORIES: true
                SERVER_ROLE_0_CAN_EDIT_WORLD: true
                SERVER_ROLE_0_CAN_EDIT_BASE: true
                SERVER_ROLE_0_CAN_EXTEND_BASE: true
                SERVER_ROLE_0_RESERVED_SLOTS: 1
                SERVER_ROLE_1_NAME: Friends
                SERVER_ROLE_1_PASSWORD: secret2
                SERVER_ROLE_1_CAN_ACCESS_INVENTORIES: true
                SERVER_ROLE_1_CAN_EDIT_WORLD: true
                SERVER_ROLE_1_CAN_EDIT_BASE: true
                SERVER_ROLE_1_CAN_EXTEND_BASE: true
                SERVER_ROLE_1_RESERVED_SLOTS: 3
                SERVER_ROLE_2_NAME: Guests
                SERVER_ROLE_2_PASSWORD: secret3

    cnpg:
      main:
        enabled: false

    resources:
      limits:
        cpu: 6000m
        memory: 12Gi

    securityContext:
      container:
        readOnlyRootFilesystem: false
        runAsNonRoot: false
        runAsUser: 0
        runAsGroup: 0