apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - apps
  - auth
  - core
  - external-services
  - flux-entry.yaml
  - flux-system
  - games
  - kube-system
  - media
  - networking
  - observability
  - system
