apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:mdoL0asG0btq5zY6lrUzDInamGqY1ZiXN04f4hYq5YNZhqjp+htWyGSz0Y4d+gJu54tNFclMQ7iZK7h7AHbPMDOCvPtQk9I4JTbvcZk9TVOJTQHKrm8A4qEhx6LVbS36p+IXFsFyM3Jp2IJYVj/gU5Fm2g0d719iX6xiL552TfolzA/4yBpYproA1JuggqpylV/n+xeCnwgArxe6lGZYQXrOhsuOqypVJuc+pwa0zkiPsXzOocQVcDwi1ImMUbbfkvFUyWtAnMBa7bAo8BIP6kolUSlc/Mw4WG60hPWxudA8VVzTTNe83DD+w3B1c5zhJ9FPQnjwxVkn/sWITW6JJpNYRN8juFCJ/F/ygjMqqoZA5npaThyY4OdWBOw6yKyv,iv:jZpU7fpBclaVL+cXDUkRUHPdS5KxkrdIHOxADNeb1f8=,tag:azeJ2FvAcFfUQpoFZDPW6g==,type:str]
    identity.pub: ENC[AES256_GCM,data:GDi6MUEC46RLreMSMuzNJ8ahk/iwHmYMA8SKJTyc65hjjoYJZP6mT+26/2kuRUtY7mdW8HF6WVUtY6oLvfJbwNpw0foldCTYJAHk1hiD/+mC9BG3eteKVp95IolVupc3HuQ2gzjZAxt9rcYND6O2Kf7ASDna2IrqQeBqj3DZwH2dZ+sgBsJPQC2J4GbGs6tQ1/KBSF6o7sHt1EaSNa3kkcngWujq4MweSMOwZKMJYZnokjVG3uIOLTtC4EOGoWyw6YPlYNjRqVuUnBRAAA==,iv:Zy5Hk6m9nUqW+qgbBlwjCc0gSlS1K2bpRa3QGqAe1gg=,tag:MgveExLMmZpEvuUCWjinQQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:UUNel3CvlQOT44Ct3oY2SO2UQO4VG9Op95btYIxSx5na8lLbHzY/PfUhZSfBaLjPRIVm7iVHGXJU1B7/bb7v7V10m6d1vLQ0k94jhCiChtTuHWDDdrhOMWsLS5w7eDdSbO1Ir2GL47wp85ndr0rF2/iNDdkymWAHkeud20EZZl0i71SYtS5ofJO/qclK1jrQhfTZ4vx6Sdp/TL053NUihQj5OD0A4sM9IGN8,iv:cSskcLdd9tb10rMvr/B332U+XRrBBTIyPHpM69NtSZE=,tag:bYGOC5yg22Vclm55H07V5w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dpafzlyh6kar7u02x56k2g83tmg2g3t8aglwzupku8z639gqx5hsvts92d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEOGt4MG5laEZoRUdnWENs
            QktYTlVDUFNHN1VyQUJCdzNYcHFyQ2hrMm53CjZ3dmU2ODYxVmJ1UnlUNnFmcUMw
            MzE1b1pLQTVFOTIyVHI4MTI5MmVNeTAKLS0tIExzdk05SUxuRkZuTkFreDBvd3Vt
            MGJYZjFtMit1S05BeTFTaDRSUStHRXcKejpReKtl1+8mdbT+gu2t/RKBbtLooDR0
            RW6MOS85FqUDvrh0ICT6C7OoPU7woLyk3l1FkuS08vapWBu7DV86UA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-03T05:49:06Z"
    mac: ENC[AES256_GCM,data:iluk8NMTKD5WgcjUYKMdQzA5GHGBmWMLUC4lBjfkDrL0BLfy/uQ6GGdpLCNlD7hCxPlHRM+2eVqVcckEDJmOEq+vOhwhlICAHwMGGQ5q0sBNa87o2B1F8OBuTMS9aWNlTrYnkk0uIW6sZbGCmNPc5tp2tuT0KiwIna06BDESyr0=,iv:xHaAdZ8S0tgYTKRx8cN9vHduArdEnKM3+QqfwlFNdkU=,tag:nKAsOd3Y3ovEdypn8lg7BA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
