apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:HBj9qywWfXMay+GMgfxZyJ8BGVccUNTtQYT4fXvvIXeJg+5bsrKc6EnQJ548LS7mi3H9eKg66AsdHalv8PhTsjRgvHlifAncz9/FJj3KRS5qdcHzSoG+5DotxHKksoueRh31Qlpxn9Ns1pcm4kl35OOgfacZWRelCQpXmkwjIGEwbWwe7fC7Hro0Jw8aARos7Jbya95mN4g2Aghmv3RWl2Pa2oAF6umjRNYsxrXeapzlrj1MaA5wT7Lv0N/NoGgQUI+bsdbuMKpiNULT8lKRSrCw2Qwv8WoMFZ8dTgQV12kC8M0txybWMoENp/PeGMaXh/VfZuaGvaDhPWw27XRcrxD96icQw1olCO+Lbmp5sBFn1AhFsAJO68dC0HyOdlMl,iv:R1R2lnco+0oIfAIKqph/FP40EZKtfdM936IJXmv09Zg=,tag:MjpRWlA/WaRvKoBTsAQ2vg==,type:str]
    identity.pub: ENC[AES256_GCM,data:DEy5HX7qzUZkC3ryCkwezbVjP7lAfMDb9JhmSTsxikk8BSfrSkzlNiBWw+Y8OwQT6WGAdoERVGsZIfcygK5o4qqerIbzDQcZAvxHR37XdL4A8b/CPdO8eA7IuuoJOpZPT8+Mhff4Oge3PajfJMxO8IpvBrMH/BfbQaUwM9zPLNLEahaCC5lrgL22TQQ7V3tYHmbLBnJRJCVE3qG58m+rhYyqugV2XPjfwTAjWXwWKFiUcjBEKFj79MeKU0YHr7X7qjgwNtdBE9aPxtjrJw==,iv:cgq6BvwL7/vENDI550ALEjkNgAm6V/+zyTA/q1js9GQ=,tag:gw44+/rlKHBVTTHv8xulFg==,type:str]
    known_hosts: ENC[AES256_GCM,data:H9bPUJ9aSuXDexWYIw9rsQ7PfMNle5DJScfD6Q0Ebjn0bsc+spm7us63E22f0HY5UTvWC3d7PXiTYIp6JVou5LbrcFo244KZF7IowL5aacBNI9Lscf5qh0Tcn7oJaIYeGgqWKjAoPPoZac5ujtD7w6R221UJfdxsxI/JgchSoeBPAzuQd++BUzwpOno/2ep3e2F7E/sor93PnwkD7kqwET14XbikuCvm1v1g,iv:bGTojiFy/bS4KgaeIXqtVsbTYqHlCTBFEe9QwPAuFro=,tag:DonQ5u+harv/EHGNhua/mw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dpafzlyh6kar7u02x56k2g83tmg2g3t8aglwzupku8z639gqx5hsvts92d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTYWVNUENLakU5WVlKeDA4
            RVdhUUlYNnBsNDcvc3MycFJXWG1Yd3ZXTzFnClNrU0lLVDRkdTBwRFZWTGV2b1ZO
            cmphNTE0a3lJdnlXekJLUFYwV05NRzAKLS0tIDNoZlBpQTFEUzNBdndWcHVaWklr
            RXNtN0grd1JQOW5DeHE4czV1K0hQZzQKDfBoiH3Tfj70VGh6g8HYzkIWD82JZ5Cn
            U09WSvoU3hUQ8kpmTBaTDAak3TFPPNT99EUN+3VoREXRa65J3HF8hw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-05T10:18:05Z"
    mac: ENC[AES256_GCM,data:gxNZzyHjGMYK5OXgqrNbtTCDrXxo0AkfvJZB1fIKUqhWHaFxoxzwU7YpCqffRSHu14FJeCw9QoCISU7V26iDXibn9jZR5EY0/8bxqZbjSuIfqKrOEMqcMsNUBO5gkgvR93kX39+lOMrYZJoRae8LUAW9PyWAk3+srya8W/isMwU=,iv:Q0991PVE8ysTTayyOvIpa+e7DnDfZAUJZzPYDshxuSY=,tag:88tB6KQPYiYooKdqwnFbzA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
