apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:8DVRv9DKJjtWtySRD/jxA4IExsuxn9F2d4oHNtglyDpNLEoj+UHpebYRE4Sh1NlENdvK5VirTjL0KngUdEcggNKW6/VcnfKJMCXnL6yvqI24yxLULAkd6IW3zqpRg3k1dzGBR5CcDe8Tm5q3lFaaMDBp9TanrGHtsPTJbqyUW4i1aJvqMM/o+lPauwhQv7/71ZxFGagIVuPWe6EUWoddWHb6IqXKhI2JkRHgUJ6xO00d/P2bsqTlV45AbSQUO8gu3/Busgz73QwqaFb60clwVYgWfkPgTjffU7eimlRaxq+k0Ss/vgdO69RoDwR9DiD+KQ1b8ZS3ihTg1RmDNw3ymn+4OTgND67EW9Q75yr/RfXneQvxPZisp29OkNVpEZEg,iv:C5q8nxeplxY0eaXfxkvi0ElvYB0Uwsxk3eMZ1vjfS3k=,tag:b+5IiSKthMCcULflYo7xlw==,type:str]
    identity.pub: ENC[AES256_GCM,data:5GU0D5WZ4IDyvjBkjGt3fStHNI+ceNqsrAQdniAZhcVMxSYR0Io8Ux43TiNE0Em668/MIyDoLOdz3kDEFa0P4XzDl/LTfj7EzIRV6olNk3rIjg9rA2DZAQDFxvJfw+gHf5WVQkjwfbpUFlmg6FeMgvHTAIiUNCt/qR+UGEf7+6DUNgeJwAPchhwEfqwZNFizA488O4UxdTQQao8a1swJbBSYX9ofj49ERf519jB8xkCkQH1LJSD9VHgAavoTw+RGpbjx3R6UHfhC88OYig==,iv:igGt1HpM+fZVswhSF723ROiZRxotUmBHD7Z7FG3jmDA=,tag:eX7bT7kVEK8bjPquw0RwSw==,type:str]
    known_hosts: ENC[AES256_GCM,data:bn1CT4AOJBi5yW/4fdZG1+02l7PteOEOS0jZavFgkOVGFK0pqfH2nqs9idgL5Fop19SiwANYOOBtJcOGKgCd5n8FEpRN8yyKqpk7HJKnJnYIETvFi3Sc/c2wF4GTdmrg8VfaLq0RaCdZ687igwxZeERExJ2vHHrF7y4RzSP7uBKNwZ43KEKistCA2vQfTTbq2za8WWhCunuaMEvzJCJyLL/g/wFWaXM7VDCX,iv:A894pf+j+D9ZF2xCPSZsqcZUVb+zMRnMhPFgNmjgx70=,tag:lJ6/5EveTaw0AA++2+s8aw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dpafzlyh6kar7u02x56k2g83tmg2g3t8aglwzupku8z639gqx5hsvts92d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxL0FnTjYwS2IrMCtIa0Zy
            aGhtL0tsTGx3SUhGUVpRS2l1SlZoWStZY1NBClNGZjFpeEVTTnVad2NWSGljMVRG
            ZjNOS0xUZmIrRWpCRFZFQWJUWE1JbnMKLS0tIC9xa3Y0Y21pTDlUU0dSaXQ5cmx6
            ZWxGdm11RFVXUG0zeVBWQy9TbkJOdHMKp8NKxz7YX5tXFjNSiQHAGlKyFMonRqxb
            w153RZ43Si+NuY+X5GRT04P9mH6uVsoPixtV7HmnNq57p9CGMfj8Gw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-03T17:27:57Z"
    mac: ENC[AES256_GCM,data:X5u95gbiihnpAoICcb/xeuI7VZx+ggLA/aIHftJlFxVCHpjupiMfAE6XKwbqV5vDXx0JN0e3hBqO5Mj5FA5xumtStgnZ+0nm03Laq+Ut3rk+H1AJlQU9QnuntgaB7TCWbZQY70Q/mysXsDDJJcvjmN22dc1UXd6xOb+vyWHHD3M=,iv:mJTP9MDH13NeJp1eMr8WHZQ81KVrgaVFyX9v52QQL4Q=,tag:JV2/8Nq2UsJeses3EyfRiA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
