apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:JnyeF1Fl6DWpmHVAK7KIPPaOfEnXnZ16YmIyzPf5ONNEqaGX+RuBZp3AQhHGntCOIEWQ9biIVUbC7PZrcayF97Ft2nWyZlcCnlh6LVNlQth0cNaCr/o+epmvvIzf3gjvEh40RADK5XG8sCZfy0NkqAgrM1zUKxzXNYjXQMYCSqupyKg1+K0PLkSRL/I+lcmA6W49aSJVFsp9yprw5lnbO5Qj4pBBT5jsvU2PosvQHVUvXYCzIRrjnP2B+xAXUmNY2Gc3xj82J4OCXpZS1ieF9WzOb6Cf8AXe7z0iX0qql6wA9ORV0VEbadzIDa0tHzZH7nbnTH/yE/3YrW6vhRPbhKbjMRQbRRuTNksYMcHjWQgxONNcMitXsJvULKFOH+YP,iv:nw2CNuz0/9UhGxzyEPmSnUfAK1oJnAWa5XZkmgIlYJU=,tag:JYvjCAaBbVZRz04e2ethsA==,type:str]
    identity.pub: ENC[AES256_GCM,data:NkXBYg7iSFc+x6xfD0Fx3c254Qe960U1O6Tbl4Fo7h9hFMBAnQ+OGqwkHfT+ZC8rCJ+prtWitp2pTNhpp4RS5egsEQFC5JDXEZOTGKLLCoLIbBXFzaLI/CH79buN+9GdlWM6rePd2THqmtWh/k726Zy2xVDu01i5KjXbvX/OC+1dYn1VnkVTPe5O3zSSfWSzmjK1pHq90fh4mOlAGgIfT3DIf/I25iJmpzB/WHm3734o2gtl7PnYwN6+K6M5262nyi/60j5ffr/QqdiN1Q==,iv:MeiQn5A9c+OFrB2Dej5Bf3OMgLXqTMcIGy3Mc79yAdI=,tag:DL5ZtRfAvPxSYYj18zrHcw==,type:str]
    known_hosts: ENC[AES256_GCM,data:smTNNQBF3r90tucbXM/XreCE+b5dxJQRhd5MmH4qmTk5XMP0ek3UsCqpoHM3GUCqMJjnEGcfrfK9VuB5Oin/9KlWia4J/VevtaFXeG2yaNQi6cgsN63G8k/3mzCvROS1jZ440v5+n5Lx+CwbjpNT7mJC4DqoGr0ngUj+DQVscvZBopKGPo9QmblE00T9k2ToZXxhMco+yepPeNIgIihUPn4gDyF5ZF1UPp2d,iv:UQZ5Ib4aJSt9jubro13BxUQzq1ikwqJmxVpRf+UfxsQ=,tag:ZSCFoFkcKPVrUusj2o0NzA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dpafzlyh6kar7u02x56k2g83tmg2g3t8aglwzupku8z639gqx5hsvts92d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqd21ZUFpjUGdGalFpRVVJ
            UnZ1M3Q2c2RuOC9FZmUzRzNOZXdPdXpXTnlVCi9OQTR5S04ra3BPZXZVRWI1MFNr
            YTdzRnYrd1FQSjhxM3FqV1p1MWt5MVkKLS0tIE1zS0c1ajJWUnFKdEhZdzQ1U1h3
            VUEwdkRrWjF6UVF3YWpjeHFmR0dRcEEK3z6pPT/zIqEbb6ZCJJrHAwwhB7DgaSM/
            uJRwybSHSVCbkK1gAnJanFayCbWGNVasrpZi/2jMY9SdRI/0YcvQ1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-17T14:38:26Z"
    mac: ENC[AES256_GCM,data:hGN7/WLEjQ8qwYZGqB51bteZ7UGYNqmUCi2UKN6Um6ab42SZf2tX+EvIicUTjgq0/wUFp3x5IZkUk6++rkMljYhOrsUXgai/siBOj/i0WrgdtaGHkXmN5XbCAKWc4FSE3rj2942Wk62UoCTCmVwpRoxnXjcId1NUzh/cgI45MJU=,iv:rAL79cAGMRtVw4iUIV4Ui2KcaKpd8MJbRWDsmWSCh2U=,tag:N5KMEJso7scNB4IzftMdaA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
