apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:lHZ6F9LxLe1d2lUOov7x1pv1k1usuflpfwAc4/g1fKqA+u7y/ldRDNlc30XsbPVSoQqHQ8lq+sx+t1ZKITgQCGaAENZZVUsN638znQn2PhJHXx+Sovf9iTY0sZuJ6jy1LEzTgVd8Xkoa782bFcMYl/kH4xoi3SUTXzlltVSMrJq50u/7rcMXZyJG0/BMqWhkJBKH80NuIREAnK8El2YFHjIBtOh6io9Cpzzl/0kOiOWmUMX5Wc4rh6rS5f26yvoPMLL+HekdYEkL19wGV1Uwi6TGA+hS2KAatzXpFFLa2i14UPfuMh2MCVqS9CEU4Pz9ZddLRm5m1V44DrqB7NcFhPrc0bz8iSgcT10QWe1MCN5SL99XtcKkMZlk0JLiIN0F,iv:sIHEJf938W4eL2J2r0oKZSBAtO9m1kqH9K1y3mtwyOo=,tag:cVH28wFn8WfrDUR3Egv5eQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:GtXck4lgJZUDpkvgwJinira2uhFSDAU6to+W+a1oD3g318kfb9nprvwNBtj0zLj3g4G/uY6mXHAf1TkJlpd+5KIeLIkzEWW51WhgBD+b/F3Tg9FtDjJjQdLU3DyP+3O0UxkjYtc1EMqNkN3aXQyw3PwmcHXFs9PSAV7mIrClfTQtw24qoRFu6AYKeCACtj6YTny5eb/JX8qEwIVVIjQuR4pe2JjZv35TtYvCJI2PNryfuyLDdD+5gVpwT0nYan2hEgZ9ncS7vus6URRgnw==,iv:HTzN+0cSy2XjGBsTcTrUt7o1IjF8RYjuXxsBqwAaroo=,tag:gQIL0NIGcruQiHWMS1lMRg==,type:str]
    known_hosts: ENC[AES256_GCM,data:0XBsOnGERvVFwYsunZfkZpMOujIXEFbT/Fvr9j6TWf4CrauMqcAuYi1QHg+Z5WDGdyaTjj2WWYT4e44wbSopnTfRJA1voiWa9vOU/GkNiQeWMGaYgLVqJMIcqht9PamVS8npQeheS9Mu14CQb6iyqE/cycQtt1jkc55r8xMziqO6tgzdtyawFHQFHyPUDbqpZQn9CrejKlAYgb0Cpip3unDwMYjUAq6skg0L,iv:MhyeIt8PXXDyYUeKOBItK/ug8w/Msjr8FW7fLw1ZOtc=,tag:LOksegKFr5qz2JVskRRnCw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dpafzlyh6kar7u02x56k2g83tmg2g3t8aglwzupku8z639gqx5hsvts92d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bDJ6SjF6aUZzNUV5NHBD
            ZHJUV2pQYzB6TjFKR2pYVHZQUDJQcDdOem5BCmthRk1BSHdZYjE3ckFjNGRqTE4y
            UWthOENDRHY4UGs1S01YWXVLWDRaS00KLS0tIGwxTXoyUUF2eGlpRTFZUUxnMnlT
            Q1YzWERXbThwTkNGakNDUCtyQ1RrSmsKijDIQmKZsIN65HKpsIu7raBHZtHsD8q6
            vuBIbAOLrvm5vJAuVI/FZuxJBRUviLWlcKM9YpbGRHHN9o2OLEmFCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-19T04:32:36Z"
    mac: ENC[AES256_GCM,data:8opAR1WwMey4e8xFk2E0OsAOjz1YKBJgFJJ5m04mhbQrSjwytqkumF2EqfPD60kl770E7SiQ2ygNFndTLkE9mtZAhyhvc3xMrVz889q/v5hvCJvb0rVEiHZrpKxp77oABxCx2sikWGS6qTymJXhzd9eOx9VOo9Ust3r6yX+A7NA=,iv:rj+3dr5rV+68ngZWB1T8mc4kHxMTBdXfx2mc0Mo3c4Q=,tag:uzNqux5y+lhL4C1Q4HNa7w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
