apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:TPazUtk5RqSdK3wW1DNYM4HZWAntsUOxLybcmSZEsn4zWLP5bwY3cWi8Fgr9B44TJ+o6BuW3hxoX9bbKb1U07+GRubX8Om2HyB5vCK+O9F6taybsteASXUKr1+9qWtbzEiVGldH5XGDYsth+0u82OsOpQm5zXUDyQyU2B0t4MxLs1na3Jib7ZgaTqR/uHJX5LoiQK3kNRDEa4/X294JofXM6XirKQnXnhXrOzbfg2M5u5MMYKa2iCm0SxBycoktnagEKSANCuuB2S6oYKCB872E0hiAX6ZDYbFMj1iCt4HxcVaMBMAIRWINVSyyHeY3kKINGDsZ16Tx+xMjjFyUgWWwx+QIb/P9t2e9KckLk69sDIxamzDF7OgGahhXzfK0r,iv:e6SwYrFkyNQkXNpOPptAvxnZXBSa/vYHTNN38i5vFUk=,tag:nUWoPBI84OJlOXKiKs5IXw==,type:str]
    identity.pub: ENC[AES256_GCM,data:x+d0IoVLsG9rpKAPE0fm6TyoWthJumBCW+RgCkCinWfg54sLbw/81f4FRU9wTLtMDP75ytVwz8paqUN0cuavs+rZ8dv0aonDOh6Odt/4Lc19nTppFG089JecSD/2Z6PMrLBU5T8wxw/i0q96Thh49QALqifZPgXTsOLZZF9vJ//2n8xkPZuM8lZREOjI66qN2uipGNs/xDD8MFlyw6nYW0wAHeRDCnjP93TO9PNAQIGnYHkEvvbLIhLjmwqk4+sVccXYUp7zCGFn/4ApGg==,iv:1orkC9lHUPC6wC81eI9XM/D2ge5/E2T6AE/Ybzh7XH4=,tag:oqvj81ksiPcWl1GvLx+9nQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:Mvjc2ACWZ1KvaZzJVxGW2ITiNY6OLTnGluud+rkRd/GEZVm7IzyEnMz9H1yOIh1Juh6ZxJWPCrviKfbSpg4NNDUyzfJ47TRq8GnwXXlnZ1436GELjzAmiUeuklKQYNrji5BN8eL02YXoYLJxU1icbsR4YBor9VzIjj8UQEDsGzQBaNCtssYefjhtpDM9d6ElpwBgblWAxZinL7v3DtgR27Vv2tGIYkuooWGw,iv:MwV5jznMQzXVFeNzHBTCzhDQ9IEtmEeMOL9kuCka2hw=,tag:d3y71zrAJ474Mr+SptBhWQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dpafzlyh6kar7u02x56k2g83tmg2g3t8aglwzupku8z639gqx5hsvts92d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTL09Od1AvS2F3aWFZc2dY
            YkVHV1Z3cGx4ME1SNTR4OVpsOGMyZnBxQTBvCm1sakNuMWJFeGRObzcyTmwvV1Ew
            b2tyaUVNWWhzVENBYVJkR3ZvVWxhdHcKLS0tIGhMWUdTSEN5bW1rQWMvTm9ROXhx
            c2p2VzBYSnNjcnRWaEkvS2xGb0xBU2sKtOItxlS+NQYs/DYElvoYA+Yoqm0Nc6zu
            jYtGNYq5YUGZKBVuAyJ44gTIdEOPTXJh57HrlRSCCuOEJRcZYF0iWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-07T04:33:15Z"
    mac: ENC[AES256_GCM,data:08iEys6Kx8VbXhKSqU0ysK14Yz1MAzwPaiKgltXHLjwOG87JZOy0+gY+LFsLQUPaw38Bcd8SZH4Ele9+xnJlJfotCTcUmm47jsmNHXc1MghZNHiBoMRWFVpUWa1X/l9GK3d8QE1fHl+TxSShXIhmlBc+4CnlkCegiD6z+D/4SDE=,iv:RpWnSuRqF13NM2kLODtnCsUzCU/tKuQ31mj8xXRfYKw=,tag:X1kue6Pb7kKAKDyOnhJ2MA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
