apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:1TCloew25XziYfkfDU6J7OaLDa+6oxjtggFGUqucKC1IgpgkDfrl1bI8rzSApwgCxJsZM7dyUMifjyzOlnaCkySUNMUfvV4o/alGBhdQQZgUipZ8s545arKmEdWYMyDPhorM/qFrtJshRa1Fc7F1c1d8G55J/zrLVVCqW81btR5tiopcwsEG4bB6y0wz85TtwUnHmtxVg3tnW6uOaFqKg41sEZ6BNj4NHsDaWnWLcprT2YLs/48QKKcPnkggF/j/W0+cuYNw3D4x9w7AtyLdtNwFeVP9aUreNjWW4SxUsQXo9yjv328vXvOhoFvCV+Ygl/HWKtp5LT9jTLBrHXEIDRM0rxs+TyZuO7hwr8VyYUeJzQ+mklN2L2CYkbdhL+ci,iv:y3Ma6wsZPy7UkCIpckEEEYWAtixCc3fKe6t0EHX+rnQ=,tag:r7f4Puqmcf24i+bTW3+FuQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:c6felk9MKsO/wnfSJIXeFeUtvKpu7zBdAEWrXM72yMEBQp5eEQrux2YZXvXwSEgYPCroxaxM3QyrkY0jESrtNaQevmw9rGfQQqaziPzEYrfDXU4x6JhkurqVQiRIIgqFXHFrMzwpaz69nxXZML2lbrZg2XtgShPbmBMbI6j9ya5KDvaTm7/T8oNGsbTY+Cppg7rnc5uNV9cJGKn6JYwwj7zTQFPhRHCU0Eti4o3bFdlmbwuoot9SFpKTn8icc9VLWfBCvx3NTwszW1Wlyw==,iv:8CLl2EaPYxP4XWvi9KWd7v4vl/rdIj+H5geyOe7fhm4=,tag:Z/apuVL4hcI6/g+8TOhwGg==,type:str]
    known_hosts: ENC[AES256_GCM,data:cNx0l6GggQKgw9rzUByg87jWPVUXSfGyfTWzajnj+PHa5lfDl4cTmQTVDiW/6V3jKB3z2As8vSdFUpZnbZuAOBO+luBP1TiIFnyuEIeGWYXaXUggf7bU2ApUg1NpfXi7nLNECw8SneE4eYfyT88drljUAjQdvsjoF1QVng2fZIiFk15WKjwfN4yJRRfJ1OJbgVhDxguZlj3qT6Fz15Kgt6tuaWeZRylplw/4,iv:fDwrxMbxkwL1iOwCNoFHf/d1K66s40lV5tZ8USKSJ4w=,tag:W8X7+Wp4ISfdIF5mNDslfw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dpafzlyh6kar7u02x56k2g83tmg2g3t8aglwzupku8z639gqx5hsvts92d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyeldROXVFTTVmQnRXdEF5
            Z1J4Slh2N1RaTXhyaUZmWE5OWmwwR3kxN1U4Ck4yek9wS3hnZUwxaTJneWk2Q2ZB
            VnMvb3hvaDhZMFdPbS9pSDI2MWZ4WkUKLS0tIFBWdFVTaFRsK3k1ZnpyRDYxeVNs
            S21ndDgxMUIrZ2VyWWJDY28rRUliZWcK7ou3YoXbxIRf00wenYxJr7+RtI2iobOd
            lV2+E0Ij1umq+dDfZNOSB8CSBsa77GoyNtOfiR56lNDmiTEelG+fFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T10:15:33Z"
    mac: ENC[AES256_GCM,data:lpKwpfobgxCQrmWKiJ9iWonQh2asfWfkmkboIpwpXsauyXdte43boUw/XBSVNrgzWOCAGo63eUpx0oXwnUTY7TVkjoZ5oEXowEpCeFGXVjYp5+VU7oEN5/TE7Kypr0Tqx8rDOPbRaxnhMj7qPU9Talmepn94KoDJkKHjpyekSDw=,iv:HDpDRHNHk5V3MrmQPknvnCJMslD1MlClzU4RK+poN7A=,tag:dsBDUh1kuMrwTyVkOVb+lg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
