apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:D0sjZ0qvsJIHSVESt690ogQZK0oJRnfkg7rvTt1YUqJF9vwZAWLB1+JIsaFpa3UTXWpb9Mj+iKLEf+uoPzPC6ng/OgY/w5uHyC6t1Qw6DHvFF+nN0S4ZkCYHBpHKWxqqSjwambQroe2MtRvD27vVDB/LBza+K3pPuhD98wNpytYXlhZWeDPpEWyXxC7Ya56MnIphBSFLhHhGllGK6B+UP4+qMDAhIsEkYWMdKt59PpPWkKibipjbO0cAepFypdpvk68lunk0uq6SO/nbd/3YZf0YT9zeHBHjIr2ot/o7+fJjS2qviChXtNpKsXWcfiXNyQiCKcCAiLVUMzqpyUStHmQ6diocIhr9puiGbOJ17OjvShrPEFShSJmNL+xwM98Z,iv:RDorh+mljOFldBQBWcSC33UhNCNPGn8/EKFuzJlhDbA=,tag:ue7bQoDz/UO2xnEAkRusFw==,type:str]
    identity.pub: ENC[AES256_GCM,data:91kGy1MBV2q8fdGIRW6GM/XNYz7SR4O01ci4u07NtfH6UeDPJeWGPYbz1YNrX1T+0f//3H1ANLapB4Hc3wgyVEHUKMyGYDguKdYDyjNokQW43lR/WAD2Fv651el0ObtjaB31JrbZI3fXHkyx7af6YS9w3P7te7SrzwGYtdcuhoJbGWBUOs8+TnJwHj1Ql8DMxpLPSQPeqvPSmtUK2k8K9HzqvmwqJK44IJyx9gbmOpzVbWA6FK/2xxa3N2KXu0Si3Eq8com65XogjUJnXw==,iv:h4LuAo34qbHSzKB8YQmW6SRWpwW9cvGwggADcqCSf18=,tag:j4chSPQ6zBUXiaYGBoVyqA==,type:str]
    known_hosts: ENC[AES256_GCM,data:mCkKygTE7xRSb2kWdVy5TCKXmDaFXwwX44wNP21y+bZcsg9YS53/574m8W0nakGjIIr4qyLYNqAimS5N40TbP90loCCnPibCtQ/arg6/JEqDvEHd6QM8RE4vHogYKo7ZSZ74oh/0U4VX+JnbYSxVHOtF2BI0s1TElbncW6YLKVpU3sRcUhtBurUivoI4ZmBazoEJHXr9ytaZF0xliSP4Xp5kcgrM9/iiE3KW,iv:uMkEgV7gq2q5ognX1IaCjAEUh6Hl3gmgEHC4vZxhZZ8=,tag:bPWjXZq31gwzfIC52OPRtQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dpafzlyh6kar7u02x56k2g83tmg2g3t8aglwzupku8z639gqx5hsvts92d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGaytPaW9yUEs0OXU0Nmto
            aDZIbGV5ZU5KMkhYdERBYjFHQXZydGdhSVVZCjFZM1NBZUFjYlZOcnlPdUxmRDZ2
            NGxBSS93VUo5ZGpJVWJKaStHYU0zVjQKLS0tIHVLeVZNU0o2d2FGTU1TcUpHZldN
            Mkl2QldzZWZpUkxiN0FRMEZFUU15c1UKGxL5XcvPP9wXwpvLbgSXkFSLWRH6jde3
            aad7/4mnNvtydrJMNYWWg4M+hQEQQtLIzuTotjqs1BuwUPsCwASsww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-03T19:02:51Z"
    mac: ENC[AES256_GCM,data:xtorDfli9mkMUSqmqHxJtYR7WgdFOa2PC+HdKzIGpxt2OLq/ngRnc4qVVzBFoTiH+j5pihMOVwWVPnfVIiGjXimvuTIkaHJX01mpSz+sOonfmfqELEgZito62pRtryAGjs/mzm8wrK+RXXKkMqQyUdPwU00urp08qJuK2HK4xUw=,iv:rkG3aHpO1AN2lv+Rs9lhEmMCWNZxFHEP6xMmH7VmSSY=,tag:DufEeHeI6j8LHiqr0RAY3g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
