apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:eX6sF4uoFaHhM7HMyWMjVwJMrDqNZrjgaRsLYZHs3hRyPkm8g4tV5SeiZvqgyPb6/rjS/j77VGopnEnn9byNVNTDlolTg2J7KPvZO3uyafjBZmUjem8aE6QKgoyLmhhg/h6BSxmS7H5//Fks7aIlwcHV1IoDNMVmrkM840Xltuy3FUm9S4cjqM/648QmtQXotSqnVok6GigMfuFdzfN2+kudfsA1SdULLo6sVDSrMosnfNUWC2/LXtjG69nxBzXgVOuGMsMT8PQHroyqIWcpsWfM0MfwFIzIuSXK/9GzYEAhB9FivwFdIGT+8tzIdM9FiCM5085Krfus5qjg3n27mcDvHUx3YsmT6oSizKm3KbKsR1n0PJvEHjbhAg9OPpkN,iv:aUFksjaYFaUkCsr6JwMzBHobopvnw9k5axtAvTZjcgc=,tag:gdEbjrd2PUYDHo+ESG18pQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:g4ccab4dNF+xX34tTSBYk2qssvOwLHULYwMaibZuQdsIFFan5ChpQaj/UV0klG7WL2GHB/CDFm4daGWTMxfR4IWJpvyHIzmP/+MHJBKah0sn1UpAvEVEtQRUMHZUR31IJLUre0j+CItKLr+pD9vHP5NqHcxZaNtgGVLByZJxpFtZ7ihCTDAwSc9+QSYgPTDxVuB4a/S2RfgMICseYGyQ2u5dF5AoGLct0yapykjcFQ0G8m+ZF/Dni4MV4XEHNGgJv0gKdC9yPvlQemr/Cw==,iv:KYZ4wHqDDP1eksmlImes3IyR7bGEpqlXDyxOGy1yxAM=,tag:yZ6E/VFIW850RB4iBsvUAg==,type:str]
    known_hosts: ENC[AES256_GCM,data:2C1Btzyq2xSU0Wat/ahxcTTsMNrxIBbPY7F/MJjxmkwtntUgk0o/Dydf0Du+j/5VhNRDENrVCZw+tNRc3x+L7Ktk95ZRNDSVMtPXZ1aegK0kNWEYl1geM/Pq8LxiV24m4Sxl7ZV/WKFjgBbmn2o5v+Sg0yf22w1WGwrzdnDiM9KTqwiaNK7rFjyFa5LaP41ByWXFR93lEpib+5mM+BbihCwc3RdX/Kt2KWad,iv:rIfugkpGBFfxcbho6PjkH7mqdilwglzflbx/ezWS0Ho=,tag:4yX0qvrnGuprgw5IVh53TQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dpafzlyh6kar7u02x56k2g83tmg2g3t8aglwzupku8z639gqx5hsvts92d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcHFia2hmRlg0QVhjd2lN
            Q0VYVDJlM1pPdGtHSDJYdVNSM0xOYkJabVdRCjRQQmhSOUlOaTZGd1RWZDNlbWwz
            TWJ5R2JuS1FPWEtBSVp1bEVHaGFEUHMKLS0tICtrWFIvQnNyUEpPSThDZkNaRXhP
            S1U4WjQ2eGk2MWIyOE4wUEVWUUFtajgK6fUinjucjgNQVRHepFk2BhTI91PHxfFc
            pnzt3ULrXfPZdi+m73Rxgg/VypWwJ/Atuhz8gof5fuHB89r1WApgyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-13T05:21:22Z"
    mac: ENC[AES256_GCM,data:/2dHGdqhEhEGNPnNbkDG3cnRE6bp4fx+GOZ2wLkwxn+eP7uN4JNnrv/8QM2zLvCsSEDl7OG/6W3mabOLCqVzYp7mJPzpz/+HXmEA5DTA+G65KzxIKTCgtjNqXFMb2Ng+xxMbiyTEPmZPY3Es5Swr6kWqXCMXa19iFzphlv0xmFo=,iv:0ZPAsBvwwh/0dFXlMinBVieGYIfQLE8UTBvK0K+oSyk=,tag:k/M4mtSGVRqbBsTD9qZhXA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
