apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:hcKDigD6nd5zu3V46/HdgER7MACV/3neXVNb2HIc4GzrYpGATzorxdIN+m4xxdF6mzA1BMYDqgO6gbJPArGsMYfbUfxJUMNVEYjMFL00IwyumJUFzpMGeNcVdLigRJ+UTLb8Zq6EOWVl5JqfLjIA5wym71WrzYA/bNVO7UJUuF6xU4AzwgXkXy5Q1L0CvaDA7YOJdexhde35132lm3aKQPu2397QwpMV5QM5CGUOEA375KEwrm5IkIWNMbfN4sEhezKuVn3OwLoxfykcIdqnXOfdj6fLtGwm1Jr28ij+lNIaK/LqncJtS5ZBF1IpLnqdfvtJXa+uxamETt8YjP8EsETBOPLxNdVCSIkagTZneBrfkuPX+tDF616ktKkhdTsV,iv:8c7XmvtrpP8qonulSDP98/ZCj1EnG98tiyHRXREuFws=,tag:jtZ7p3zKdabL9lhMPrMsCA==,type:str]
    identity.pub: ENC[AES256_GCM,data:r0xJL0LNMrb4CJ1dRDA4cJXa0SqLYp1VCzajYIKLUTHfRqP3gQXNKE+nNTyhRNJMe1uRjtuEaLsNtbbvYUuT2Vmz3pWKMEjlxH5g32hOkUT732kk0xTjjuCzZLl+4tqctEkTi6l3zI14hzGhEJfw5yno3P2SooAEebK/H9VympDjGO01DzHILfjcNpqfLb5EWeqqBpbT2Cu+r1M8QyCWbf1i5s3F2r1HKrx7PcQkRaoRgW6v6V61yttB+snU5loR/X2R/MOwTXNpCe5HHg==,iv:0P97VcUOdJyQFN8ePqn5j2VDplQX/zHQMpYmqCaeQ1w=,tag:toHGMqsgiO6UQBBpqgjpzA==,type:str]
    known_hosts: ENC[AES256_GCM,data:mxJPHnqL9zKOIMKgG2nkFvUhkB1w5EgYm5Lftu/L27F+9Tb7cyjWm9Q+MV6Fx4uINfMpqVFqbaLH3CYHxrK3X62xNIyDqR8tGasb0RLpFcwsRjdoUVbM57UM6f6plAWPA6pIw+qniOnBAiGtQubstKdCbOXcx7mTL35gkxCpmlK6TYiC8ETlcLL30DB+higdUyHkxiHR3ep/LODI45YX5XT8k0FxcUBzu1/d,iv:nlsGNydfT4OiGAx7SqYZbALLNysJjcPndeuSJLyCelA=,tag:8EC6ml0iUklBYhsMnZXxZw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dpafzlyh6kar7u02x56k2g83tmg2g3t8aglwzupku8z639gqx5hsvts92d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpNE1nZ3QzYzJsaVhDVlJ4
            Rkp0elptSWkydkhFTlRPVjYvU2I1WFEvM0NvCkJISXEwbDdrYTFabjBURzFTRjFT
            Sk5BZzdxWCtvS2dhVWtrZHUzRjF2ZHMKLS0tIGFpb0RuMWJMRkllaHJQblR3VVNl
            ekdhK1pGOUhtNFgrbW55Qmw4b3QvK1UKfdJnQJ37u0DMI7r32g+IaTjXdc3Je5zS
            YuJUYOcnF+ZiAQf/ar4EHcpp1nEDRtJRW8/DiX0StEb0ffoy0fikqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T16:30:29Z"
    mac: ENC[AES256_GCM,data:Wh2Y2mOsrALuGll11pMVK+9oBXgthjHKf9S6hRf/IgZmy5abU5xGsS1c9vDVNZwopw0Wq62H2BSXSuJIJA1khqqj2SIbAK5yCctTJi+U94V7OzezNbOpSBWHj9eRWBb9Jf+eNYoks6wDZdeIXdAi3hEU5N22Rrpnr1wd/KX69Mc=,iv:0JctCSLVOieE229HpNxN6KU/20s0x4UQWd4qZXObZeo=,tag:dZnyFYHTOmLDVm14tGr0Ig==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
