apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:+cyd487ig0lZxb7yyX25ygFI7WNRzcEK9yyFcEo2+5aKS3/Ub1qXJvx2ptsiY8oyvy0z8sMln34rL8Mz7/seNRiDW4/ADtjLp+Rxy1mbYTcaLvIAwahR1ti7vd6+y9VilQH6orHJmT/UeIoWnUKjcKJtp4uURq1bSgWNFE1MD2l6BYRJ1TivU2MpJCAqszMO+dBAjlNZ0zlnwzP0/eBCdfyD4OWOOyumsm15fXGOzcmZntgJYPgmSZ7MdeYT3MWmqEV7lQgiqro7eTMSZaMbviWs8/UAF+QBl+sm2F0Y0N7CYpl5EXW7JNpp/By8MgsrRNbqki1aNLNeaBWsmqmpRAzD6xeWm6uxpgqz4yrKhA7GtjFY8Bz7lhDcF3su+b+m,iv:ZnzemTDbSUFHYDPNB/Q26xl18jiKBEquR80cjzDttV4=,tag:BubXyIWgOpL1pbXkCPbyNw==,type:str]
    identity.pub: ENC[AES256_GCM,data:ZvrpqmhBJjqarCv7UnRFw2Voi3QP1Mhku4b5AWI6Xtv9a0JLpTCY+v7EypsL0cTpFDUw/K8wqbrgGsS5l2osYMgx++1GUJjIDWsJiblGMVb0v7wfODcRXBWytN+8yHVBZdnk+4KrLswWWvUGWJS1pNTrQhEf92jJNZlkUwpLz0uceC1OwCapPgcXyXRotHdbGCTUz2d4iT5LEghq5z9vHcRZcXa8PKIgjBMv1Bv5M5dalDm93alWvXFV05idm1GOsNGFCQQfGQmbWy+hPg==,iv:CEuLnmBHU5vIoSjS57x/iCQzNxR1eqwlrJQ/XCbYE0Y=,tag:RbXb17l4oJBqjrvVpWLDIw==,type:str]
    known_hosts: ENC[AES256_GCM,data:F8mQpvkflPbNG45eKHyPcrE1lbLbskszvVF+miLLmUoI1AXMTBoi7ulSOe7L69GQ1qSQVKBLBMHKqoEsvwW2ogZDRG2d/xm1i+ezJa8StDrkQhsAreS5IkfuZWznAdvVyHiqo91WYftUzHAdjsP4JfgusSc3Wgij4OiWiZ58/QD0xk1nelPz65qEcMmm5ielT5Yycl+v1N+/XwEdJ8b6Edp8g4vQnChI4dMJ,iv:dxtgTL9bKwgHDM6Z2vJgL+oOE6SjgPhD/KkJNb8Anf4=,tag:nx5676CSxorFbA1pCUbd3g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dpafzlyh6kar7u02x56k2g83tmg2g3t8aglwzupku8z639gqx5hsvts92d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmN3RFOWJzZVZYQmJPUVo4
            UjhEYUg0SXR1TW5zTXlPMUJQUEZHQ3p2elRJCjh4S0lSaEUxL0pkOVpMV1NsUFlB
            UXJJQjN4WGdUNEc4QVFVZHN0MDIrTDgKLS0tIDdTNkFpTTUwd055TEQyRzd4SGVy
            VDV0VDhETVB5TGttSE14aEFvWW9JdEEKQcEGl8tMIWl5AWl1O4etzl/EZOQmKuZn
            QzlgX9IOlZAWphAR/mbmrvlR566mOkIX9W5n+b74/J7LhAZhNNB6pA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-19T17:46:45Z"
    mac: ENC[AES256_GCM,data:7Anlm7Wx058W85ObicBPRLvFGBiz8fDlns+NcCIjK0dKv3wN5V9yVHvM82T6uzlhszZ9j9ekYHwkwTZGcuhf8F1Y9EOHkxPiTYirmlNfE+gKOejja9RHF4LiysiR3zllSyX6CczA9jOhgaxSUarK3DdNVXd8fUmPcHf/YHp006k=,iv:EX+XD3BEwV2zvC60K9cxtY2y0czH4E2xCYmEr6RGJF4=,tag:V5R/OlDRpRkuGNlRMckAyg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
