apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:xwAMDrWIXOIla9QqYkJoG2TjUhBBLCqy0cuwPNPYshs8LLQeU/0UwCLS0r786U4eiHKgO19vGaVs0kTwF18cJX/+OgTxdi9Obs/BkzlJd0rv9TiFPv9ti3u6tiQ/yC0CiCQj2TpLg/HkYneo5PJjd0UNWlytEW0BsO/nTJvxc9Md441EpBclBwobpYyGeL1ILCgVc0BenR9pkSWVDaEgZRc8DL2XO7sAPtPZrl8gpITdWjSyUz/6oaErrMv0mNb1pByrKO4IxxJpNBBfXwrN7RYfJZT80wy0NSPtcIdiFcO04CpAs/oC9xpIfMVfjXdLkTu9k1K0u2iBZAP5XfKB8mB2F3vxTg3cxL48YSqjuSd02vZP5GycvHnX5ekSDOW0,iv:QpzfBHdktrKdcKFOZt+X2vRQ/j/kNwkagSwi3hGZD9I=,tag:Md0P/2UT5bW45zgTfXQnAA==,type:str]
    identity.pub: ENC[AES256_GCM,data:jkLSdPV87gzkDkGcwp7fWtjaiS+qimcoItOJW3ehiH7I3s9qJ+EjA/uoaXmkocc0d9VJ6SEj6Yw96oPOA7omBOFsWx59mLExgiXimMKYfgbSrCp7fWi3h035+3djl9+Pjxqf6LMPxugs6P4H/ElAnhS9Qpe+SuuXRw+8Z7UGGdfLY4dKhRIY1G944zrcsIRF3H8+5QuKKJ38wCeJgzFmbgoslLamWplww0ANYAoN3P1RbqmAP+/9DhGOCDhAejzA1TgiHf/Y4GJMKuYifQ==,iv:69PRI31vUvA+VVPHe0eq+tAyhPLfOcuh2iv9Se0T/+k=,tag:M918CQR6ke4cR9ZBb7snKQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:qnsUfghG5nrB27cvwIw1M+sxUqu9Pl48Vp+FPYnceMB+5UCk+PdqpN4jhM7uIa7v6+kP/juZ+abmeVuna6+o/vNIzN97QdYTdwz+L3qWIs5U5ZvdRaIlcI5mqnlqhn4lRTkDTH+IC/H2ajOsMEzd0iIdRHGhCSL3qfHjIEwxOxtpZU0F2DX3DRYf/VKgpO+3ceytybDB5MUN2ow6Wxh+QApbneoUobkXzW1U,iv:62UJ4DFImo6UXzSgUAsmVHxrI0FjT65+WCgy/7cP8mE=,tag:iTPWB5e1InjET2wIusn/rw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dpafzlyh6kar7u02x56k2g83tmg2g3t8aglwzupku8z639gqx5hsvts92d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWa240VlVZRGNVTmh2enRh
            UnRBZGpmRGwzQXNlZFNkcC9DQTBVMWx3SzNVCi9KbWtXeXpyRHdJcG9qek9DRFhH
            NGFMa0ppQngxVTdaT3ZKaWx6R1RVSFUKLS0tIGFyZUs2UWpnUlN2MmluenRMM2NF
            WmZUVFI0V2hvb2VJVmxsaEhHc1VUejgKx4fC+xQZy40av6HCcxMdmozZJIkNnsHg
            lezbTI8Sr6PZXHL7eIA07sPP6c35QBwear9HiE80fyBhdR/kSls4CQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T10:06:57Z"
    mac: ENC[AES256_GCM,data:jmu+OqYTjLq49CiDvojrgXgxXfXOI2sZjbn5zi0dStruU/HHTLr71lcHafPNGX6/orfJjRPz4tEZcsnSoQ4eBUXOi2uz1s65PQRknb5Uouo+uJoRmvZXmLIL31SycNDfY1RCEMCumD14no/pIQsGBD0hZSUJh0cSFMKtg8YDyYk=,iv:ssIJZ8tp0Ibj8NdxWMhPVgrye+MMv2e5I+x8S3YX+T0=,tag:X6sIQVEYfDLeW6MBT+U+jA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
