apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:3eCZWDZ4aMo/GdbG2L0PC0Dgx8KLxZNDWaZAUkp22eHJFQTeGWJGRKiuYtdid26WxBoyefFGG9kTqB4Wi5JZ9cjWakQ9mJEnpcpYuRgIq/0fzFRsrlAZaGmZX73B3ZV5sfwG0UZrtAna+p2o2yQeYFag1H+BW1yHx+QyhCsQWveiri79iTod3iJ2yuXzTvO5x67hEIlNuvrT22PdPM7odBodewtOLDmeeR2MlrMSjpMDWi4fqMcad3qf1aX9CK1wQcowLXcClZDMNHijKguxtBR2ncR+prwpOGlRlcAjHSlKnVkblfyzgbPeBqtNi4Hegh9hbDBA3Dfr1sj0lW41YbYnCNHgo6ulf6JPtt+uBfIuHbZjevzhIQT6zFjgh3MB,iv:4Mq2J9kRhnfrVnKlxYBnrTJ0XHM+ZItsZfsJi0HGHDY=,tag:4DworfPmSqX5/R3b0cVPjw==,type:str]
    identity.pub: ENC[AES256_GCM,data:/lZL9ldBYmnEx0dZNNoGUpoGMc0zpwCZ3QyRUF4EoGTDvadYMt9bGnWXY0K+y3ruZb2H6kMLGz+IrjpZ35Ots9L+zHrhAxV8TLfPisPOt9w3jxcr6N1vbWXsR/niQNgCfBPNZ41wO+WSvXttKoRdvxNEXn6Ua8ckSDl4cfn5B4EVH7kebWrgJzxiMNAt2nR6U7HZJPLTsdKz7kGrbr4YtgNB0IdhiD++BZ9vTS8b+hPZgXftanF6bFWS5Vf1QeR3QoSDyMh90BDi6/FK6A==,iv:XAKw/l5JK174Cc7zW8+q7jpY3r+xLBBFpl2KX/sjvi8=,tag:OowHiwu6qFiqgo9vV/cxdQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:uz868HPnzN5UbGias+42mpgoV7wR1Kg7JuADtCgS5456HaMtKmztyrduLA3McgD/Y6H7HOauvzA3M3xrZNNwCPfqwQypGNA7RA9ONPB9gazuppTp29FGGv5jeQIrthvc6gJM0avQEQ1MRszrO5VWmUiXUE/zenPatE/8Md+WJG/qK7ifA2nUAi96KadB5jTWlret+O2MvQPPFGv+A6djtN43iNFH+3G3aOIc,iv:EwgAAkcW+eybnry9LPtvRToEbDkRk1hQDIIBOIfToC8=,tag:gEJkTNyIom6Mofifo69ZSA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dpafzlyh6kar7u02x56k2g83tmg2g3t8aglwzupku8z639gqx5hsvts92d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWVUZVdmp2ZlBydW5HY2RJ
            ZnNXZzFuVnJUR0Q0dlY3RFR6Q3d4clRnTG1ZCk9JaW1KeUkrZDdSc1pWMVJWMEFk
            OXBQTGplK2E1VUxkM1VQZDF4YnMyTzQKLS0tIEZOWWJ6aEh3YTc1VE85VHFWZGxz
            RFNGQlVvdTZ0NnQxVXhUdXFKS3BDRm8KU8PCQLa8TwCTvEjXj9CqUWW4ClKqhaqH
            v2xTHhgn1v6r7/pp1VigQelh/xKv00dSgU8jCByecK9gyUC6LXWvUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-12T06:08:02Z"
    mac: ENC[AES256_GCM,data:VPXTCzdMD7bmVXWKiXqoZWJsX/z0lJXaZKSYDMCFQyjZXXpDSSeJALFKai4vPNjw4i0Z4uzkzXaDzC2fr3P67+jaWP8gDb3kwdvNQoREm8G58+IGD93rp0YE7S9Jy9MyWXMkQARCHc5OI+MsAmqAurr+N5+RIwo/JoQXiP5BoVg=,iv:5e8ea91TF1ImPDosx2LdjsgOcnwy93vGPZEwoZSFAjI=,tag:ovCSX/5qykK1rWBX0sDM+g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
