apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:0jK6GHYwMkrGEmsHe7Krguc+odKz34/SbAXzXE1ZC57wWLiq/2+Nzb2nEfwtDu3R9lq4IPLXCmqpDiwiVPcRNBUHa8nFrnJSzrVT/r9dP6gED1xZoyQRKk2GJ5JipLINQOqWfk9xPWhsdPlZZ7B2kpCd+fkzdwIzlKMzx/DZfKFjOfSL6Grfo2v1f4bnZHsCsaSvmfgksuQriK4gRLTbdJV+rbUybdbyR9tO9tZfBovGOPtX1/Es+bRZnEQVh1ML3/3IRxay8/9Sv4zAcbGkn6Fc8D8EfHsoqmB6wFWHFKvs42f3Ui2NpXDNCy0oPP91wdArRdL1aeoWkvwYqp0T8fkTNYTHR3o+oMBo+43K8OUWAsqgS06A0LDsYsVd30Jz,iv:vzGp4G/lZeACtm21LgntTGQGdCAajBerTkSo9hiNArI=,tag:G9EMRgNKktO3SYP3Cr++EA==,type:str]
    identity.pub: ENC[AES256_GCM,data:8ZsLQzadTQgMRWCmQ2dHNQT90bbOKuEMXGo6veNfQIA6p5WAkXzNIUoFlRsEaog1TV2RIvojEl6nYxZ2iEU1x7JH2cz1i3lAqJJbNYfCJk6u0sdRi+x/R2EumH9vNJx6S55Fa8w8CrNzPdMjG5YM1HrfhNIlhEXpMkQ6ajGsqK+GIRV8AuGB0I/9t0O6ZTQ0euaqMFYQPPdvnrkQRcUmS60p6O4XDkfJiZOYSTVQLVwxHBHy5TH+gB6kLbNJoETo5PVF2ZsSgsJsIdiq9g==,iv:XZEgXmQYsQXIdYgxz0+q9LLu9Bzm9VQlakFZT8USMAU=,tag:YGeV001elCshMY1TJdXfSg==,type:str]
    known_hosts: ENC[AES256_GCM,data:HCEJ24GboW8T3ga3KnWWm/0Sda00ZHpXR4lB7wwOm1tNNPHFyNG2Qi0x58j/RdTOIqXFO8K+HSjMnnDC7BYypbhxkzoqgIARVz5JASqrjibKzAjn6BJ0ZaZxmMl8V4O5JEDxqh54n5Fjh3+8Rba715ygBGdwSfOwsni9Adk9Pt/obT3EFPwlr7A/M9WAOx9GxFXzkB5c0UWz0v2VWpf1PZXbl/jNNCDgWULI,iv:u/Sxb8BDyL9gvr9q9/mvqhUGQ8FuXHoSvQF92/yBV0k=,tag:+vCmFOFuiPZPavoIq1QTuA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dpafzlyh6kar7u02x56k2g83tmg2g3t8aglwzupku8z639gqx5hsvts92d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNYlh4MkF4c0lNcndzNXcw
            dEtiMlZhZjZGY202eXRKZk9QaGVDUGw0eDNjCkFMWjZoY3hZNGtvV1hrVG1scnlE
            WXc5cXkxTnF6dW1vYmhKd3paaEdZLzQKLS0tIGhYbG9ORzBLd3k2bzcxRjNqMFhm
            eWhPUjROdHhhU0p6TUovaUxXcCtnTDgKZ7C+1yuRIISPKUz5GYSGYdfWorysfayP
            zFeRPAbZRpomILxzyjml9ArxiMCf3DlIVjdqQhoDxOlgUFtOASZ/FQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-12T07:11:12Z"
    mac: ENC[AES256_GCM,data:/kTkUzDPybHvfzf+EYKc5gSonWadSHvHbQYJ5DnQGInt+3lHDyYDhBQ0TozcVSBgT1I6dnPrz6JOwi7M/koP8E2yuYZr8KHgMNGc/jJJw+dmRSCAMFfethE5LWV9Zh9CTs23qRc8tfgBYxQjCOcuW/BY+PC+Os5R7kMLbwBp/SM=,iv:+eTWC7YKuclt1yQxYP8mdKoV0naLKVVUAY4p0K/q0+0=,tag:2XnXqG5knxWjbgtD9CKcjQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
