apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:WDDOnkrZszURSHEVTrg7soBP2qGd/GLLeimRXGi3S5h6e+ZQNvWtWZpk29kp1WWZuJm7OWajJMliG130f/eTUO+C2oSKkJq+eMEHkA3bLY5BVk4cLBsRjEZyvt0AH9530YM889iaNjXoaQ4Jf+u1nVbmz7ZvtSPhB1Qmhxc5BqZcw+o6qlvq+pHXtq/+WH3jrjVejhgJrfoTgLztN8Oii/8zKvw9x5F23pAsXyLXh6hhpApsbXXh2VqR5FzC4ORyyyvIGwhBsjLAwM49WjEiVTQQnGuOLMKp3SRZsrWh1dDc3a6TbUcLFWOqV3n0nz5GtF4hrmv3UqpBfZxx7mfIUHE+76ZMIceNapmp2mnBl3vZCBvaZkzJiFqTJ9TZLcTn,iv:015QNi5mYnbAal3o3pYzyJ4i0OIfNOjkVYMitr3u3tw=,tag:/lcyxUC/N42yVPrdpEQfSw==,type:str]
    identity.pub: ENC[AES256_GCM,data:MbBsSiGcUpW7Kp9D0+8dDD3znZS8v+TX9sU5Zczk6kFtzUoTfh/541A12ZjXrZtv8C5eYHmRgA5QGfbK7ZsDeq1ddjEsehmasAbpujaJEnppMUTNpjwBmJ2lNAwlsRNIXqCLB7XkkAVoWszyb4f9gINmn0s1flwQwf5D6UzdsWxE/VlOf9eoh/DpCDT8v5E6jBV2OYByAod4CH7xl2i3wU1p0Hb+nUm7OKaGyC7TpgMcF1rk6MQDO0EyfK8axJtF/rxAywzb0xQnPP9ahw==,iv:S/E/YuXs5aF3CCOrBRYdx41quo8oNxVP8Oy47vUsTcQ=,tag:LjmStMmKUjCajm/4fLhrzg==,type:str]
    known_hosts: ENC[AES256_GCM,data:eLEaPfl113d0VFwaT7PalL/hoJhaWfukLhOXwRwxWmX+BHPXeyd361Qs8m2JQwxpzFPuERHmYUNbdlgO3FMPmUV2QkkrhVj/ZKpC2Bnk/YWoS6IMAXNfzo8T5JZSkIOJOWwHq0Rx+QHtAoMWRvLj+oydbPTvWD8VfAAws2IIOS4siYVMMyqyQU076NkZa/SFY+zVXQhmjj4kr1VKPAC2mqA6XPil/4Oe91wg,iv:r1QOX1eymUfNXrzZ2CGIbuDHLtqU0Te4oHICh1Hz6p8=,tag:EtZQ2u8Xkg1e9qLlTAUnHA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dpafzlyh6kar7u02x56k2g83tmg2g3t8aglwzupku8z639gqx5hsvts92d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBNmRueHpURzVTMzRMZlJw
            MWM2cWdvc3lHcDZiSGY0UGluU2VMQjZhZHpRCjB4eXdmRXIrY2hrKzBPczZ4K1hq
            dlZOVDFCblRvcTBGNFlQUWszWTd2bGMKLS0tIGdKR1BROWJoeVd3VkZMeTArUDhj
            amZyY0xGc2lnZHlBN2VPMlprUzhLUmsKroA579HuXRxI3zaUntpmtZYr/S7vgjmY
            7nh5Dhui2QY1pnwSDmfEKKsWxK6APvBGgB3lLFTTaP+i4dAUat4AuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T07:47:25Z"
    mac: ENC[AES256_GCM,data:9+7EttP9zJPy34+cfjE3BhHJvBjAMiW13Btv2G2J3wouPtkrYiBeDcOn4a+qBph7EQ5Yv6ynvDuXj9p3qkrFkYbaBvE+xNFK/4E7lsGytyppATgOsH6igv4/yANvZFOJbkZc7odqffJknnIUacdjVD9RKixFbFftqmcwXTaE/Lc=,iv:Quh7+GjMJnY+sZHUnPaSBc7+r1ZkIJGQZ9N6rE2i5sI=,tag:KOl4GLqBo3HUk56OCEYvmg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
