apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:s0P2kIzs2RDphxjwBxPftmRPTVd4S7k0aSFDnmu0no9hln+SJ99ZGa75dSvSH/ahSlwZKXjVGtcHxl03UpXO0nWQrJ+Hw1sjANCYrlG43YZyQXtEHZAO68/QlPboHhEp/QOSdWj87me3U5Zd6Og9WdJwaBCQiE3QgA7BT7EBKlOGuYpF6mm0F9QH7Zoq8/mmlmGwJ4/pCk2bEfM7mEgSQ06wQpgRD6YiSIfe0BJ45j9BrVpyFYh/pquSSZXBFABMyuGm5UUufPkedXDrFUczFO9pNxNp6r09Byr3Iowx1BTuN6BlYvY6VM2WC4HsOY8yAA8rCbwez3bpfz0yFaKgnUAWpUAk87MEjtH9/14BisFrb2XTFcjn+McXgqNRwxiG,iv:sz/8qtQ+1BfTWeJ2j0E+dMPDXhpXM/LGJzqOwIBkyXA=,tag:wg4ghQd7Uo7hunLXtX6ZtA==,type:str]
    identity.pub: ENC[AES256_GCM,data:EZc8Yl9Jk3WSgnVTdy6Cd+NxvXXQ2usoCI8HNDZedzI0qDII8lD1+/fmSE8FiCpj30/H82Z9cFkBiHxxqgAJgtKZIn3747h5Bhx/BcRykylKlNbvUUvZIMxf0gcTOuLFO+mc08noDJG070K+lm7e0NYLxOpHHZT2JPNwyoTdRcDYDojwoM9yW8V3T0bhC9MDI6TbBbGhAuG5cqeNa/gs1iEo6Dg+leA8lBtgvtKvZ8qnRnosF1+we6+Dq2L9y7uL2yf504gD5E6Pg7hovw==,iv:C9nvLPA9NnWW7W03ZlGn2K0WS9s96B5upxdHQgB8Ni0=,tag:ERwWxsz5zPi8mtW99GU2vg==,type:str]
    known_hosts: ENC[AES256_GCM,data:unZSD/XhnVnsDYWAbFNx8y2c+1CF/fel9RMZUvhK+1evelSM2vmz0bsJXzVjmQMgxbzQnRK9nukCKey3IOyTRWIf9vvGMFFiaguMKJ0owfTqZS++L6rdCXdZ6Mtez41u2H3tGyV6vdb7mA/NS275cG/9d/5nmTL9XKiM8ZeScRvnVqc01KSHCtFaEi17UstT8cqRb5IYdcyzz3WJ+Y5SEgWcPFTJOPDjC8is,iv:M3vhJkyttzNWnghZ1Q3WOfozcTqoXt7cIBelIES7n0M=,tag:dbiSIW4iMnB7BLfsqRhUbg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dpafzlyh6kar7u02x56k2g83tmg2g3t8aglwzupku8z639gqx5hsvts92d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBybjhNcVhlOE9PN3IrWXFo
            MEFWZ2xmaHlkeXNpZlFVLzhnd0huZTRpclRvCi92d1F1RlNJRXVyZGowRFlDS2kx
            cWRvQk1ucjNsVlUxajh2WTZLb3BPdVUKLS0tIHNMd2RjUWdKTDFYa0U2NGtqenJj
            ZmdwdVFBVmNabUhiemV4T29HOVlleEEKBcIhkCDRTW/1/h1ZfOIWNqe6/nQcxzG+
            r0LtAcIlVPSgIYqPd2ukT0ULwJkrCn10/Ni73fltCJnwq474d318Kw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-07T06:01:23Z"
    mac: ENC[AES256_GCM,data:nxiKdLXlfLyoQ5YgD/yaGk6vL+t/CDYREjKYaqWFnDY7cDdljzcvWRSWB60eyvdNQksJ+tXZGr1bhWIiFBNCVxvvgaSZIu7fxglDfzzvmB3SLfnJrs60fD/q73/HjIHopYManTu0h48qICaoZRfa9ayaY5VV9gIzWJuS3L5LBUk=,iv:GIvr9rxpPAC0Dj9HhfdXDxXp6ndlVqtiv6bVi31SOJs=,tag:+SZx4Yl63b6EcnLw1KCaBA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
