apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:daypTLWtgtz7Kn87cGUHYJQacw0VyYnCREIHWmsinOuKy/NgqoywP43VRUXmsO3b3MkfkupVhvOefGvwR6/koCVcc2aLTYkGdlZ0aKX/ft4qdU8Pb7aUyEtHhB7xTNAC2AR17KfxhdG6wdaBG1T7hwAx36ouU3DjzTyfSZ7AcQrmojxkDMwy6pP+AxQfpYNRLxLWXk518MTd6SdQ1Ka+f4HPFCCHLWU22RojtrTJ7ig/k6whHh3MNkSEixF+3DkiVI1EBrVJShF00tRyvSKFgCh5yz/hbLrIkBz+5mGXDx20m6ac0KmqFSBiT7sgLoMb7J31StYK52htZcJ5Sa3BlYbZWsYmufX5LaBKOFbZkgf2hajvkHKiB7ZTIejmoSbQ,iv:HL2rjvEsqxHM5sGOfaVNQopWya5jmflyVVZqxkLEglA=,tag:h/cO9q98aX+gtRfXSiMJtw==,type:str]
    identity.pub: ENC[AES256_GCM,data:x+39wLu625I0OOsuvBIR46FvS1JjvdG2Jp40Fvqe9VdIO1mImKoMttfCTRnJTVWKIpK6QdhLoamAROdSH5Xqmxwow+WgCuSTZtybU5WPXj+hZ6VAQ6TWF9pwk8B2KqzPoIL8AupPk4/hHeRgAk5ig8NSPDzralJgxtV401LKfavAblJVFJtbIVgdnGsjvXSSybWOu2GzxsZRnHerAZ/Z4UME2Hb17Y9GnuVgrRU8FwggezCpmEBC0QxjXPNKB/K512zUOrkBb8s/lMdJfA==,iv:noDTIpmiELsVjm4bgt521oUDlyHuReviUGQO1XV5jQs=,tag:oYl80tBhaWor8kqeAT7nrw==,type:str]
    known_hosts: ENC[AES256_GCM,data:WY2iJ58LosSsAWfPPL2H/mMWx7wd1RzlZ3Dt3UHTWIk8Os2Ijv8C0HsQhfRcjNgs3cPCj/JjhYZ1DO+txEVu2MuiaHTSYFhD2M72PZsNorehntlRFEMt29+06M4smgG9ozIDwYI5+HXkwcn0CmQL533/fkJPJK1SXA+QjFKzguHUCl9xX4F0veS+0909SHHaWfDUTxsDI4wxoFocEQs6NVnU/WdtINSerqWP,iv:+iqZLVEiffb7E5IZsQujdVHVT+h+m+CzHmzpSzVQwOo=,tag:DLJHPElNfinAUUautp/N4w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dpafzlyh6kar7u02x56k2g83tmg2g3t8aglwzupku8z639gqx5hsvts92d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXRk1sdnQ0R0k2VTY1c1BC
            cFYzT0JwVXRCNnhRWVFWOEFpa0Y3ellFeGowCk1tdnZ4dU95VC80bng1VkFFTGVY
            cUVGNENlVW1WSndiMjF0VTdESVRSMDAKLS0tIGM1ZVN5TjV3TENlb0NiOU1PbGVK
            alZFY0p1UDhRaGdIUzRnbFdHSEZ4TjQK26TBPaA/JW9lWstoHKDSQnXDSiqyxDed
            pz4U6yx3T/OgLQ0qBaydoI0DSiznQpRR5dblQwDvJ/6ggJpq4xK4yA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-12T06:45:01Z"
    mac: ENC[AES256_GCM,data:Bz5619miBdTraJagzXyPgcU7Sa2kvhF20aEB8rNUzG0oXBLkHBRBigQ3ORFaR508FJgJBz4781vv38Owek3ycTLxal5jpBg+olpGHLccWGiAfgcURzIrYZ+QA3L7EQP1U30Z8EMC3AI8ploxfL/TpRCh30zMfISyQc4dx80uCmw=,iv:OY5CX4ljfCr1534XOHbX0Lc/RKnBBBMn0PuM8C1lwUg=,tag:MkpDfWjH5FC2IhQhDUV0kw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
