apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:5AP4gn3oJxk252Amk3SPbhITB+S7PSW3qkK/hMxW20192BjLZji1xsHzmLgPK9PNH1YxrQ3oZ9N1w7JDSKf6rFaynLjhYdhIrIof6+ITsgJNi7lzqIwWgHZt5ryoV3VFOIHfAwN+rmE34Avm4qp/e80wZlLRlAboEV94Zb/uYGK7ixeJ9k5fSbFcujCkNofF/52Hldn/B044nsPWbx7ufIiLxpcHVVbdxNVZkxuGxiVKphSlf1/pHmeMh4J5v86+t3wT8WCYgvL1xiuZ9alA9wFgnRT4wQqflaeaGXmKhDUmHhmXSKlJWrexVjEJAFnGAlxr+zDdHv/SY+OM6rk4qPTLkAwKaIf8p32CRhPSQm7n9V0KdUpjO5HW32fK3wAD,iv:ps+JuTAx7dJa2+TW689+CwCIXSJgLP2qWmzxd2gLApo=,tag:hswllOiB3G182DRQIA7cjg==,type:str]
    identity.pub: ENC[AES256_GCM,data:jS2RELE0eQmJlFObSKKcWtlKSrNdh6oPJVbXbOMSVCFFzLLw2dO2a1Z8sLKHPWUV880EwQzKJJNZiiKkas1BKskgtGBJf7PHT0WmHO31pGXPvNQ6qOUJfw8BDuQoU/qs8he4AfHBiBjBbgTg6uE03jbFScx4GtsIDBKWGHGx9W9m4XZc6dTEzodWiPGixF4q1S8oCQhc/qW2jHb1vgPA4yO1jDbfUTSmSvkC6xsZ0kF9XHh7ysRiib5xdRjwBlF6b4Uw+Owe3XwLU1EyHQ==,iv:TYJDtONbvAYeP+3vTfMi7zEPp63hJtrWZVhmP20JLuA=,tag:Bt3387q4wvw79MKoeqZqeg==,type:str]
    known_hosts: ENC[AES256_GCM,data:jpNkVV2x7URw7rPtNHGhklHaKLydT+v9jRffLoonDCnF8WHd0T+oI70rqD+vbGCQwyEzpfCNNywr1+omIL1MmNvrsIRfN7qQugohm4Ib6p2ej/Co9mYNbO2tcWse9gcuE0ZrcoWyBSFQ8u8fdaBe0gT5EzbTAWm+MMsqSSikI4gulIM0i6nUVSrHyU+Obe4RfmTcWC3fDFbCQcqXRIPx/0tOn2dHRGkgclgJ,iv:S1dlPpgxK7dgzSyomWjChbFQUAakkYB/TZNOwhJP0rI=,tag:t5WqmfMPb/atqRaJ2hV8Gg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dpafzlyh6kar7u02x56k2g83tmg2g3t8aglwzupku8z639gqx5hsvts92d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2V2M5VjlUQXhIeGdhaXM1
            bllmZ1UweEpVeTQxUmUvRHhXTWVXNW5LS2hVCnNGSkk0aGdYd2JqbE9Ga0hhbWNp
            VnRzY0c3SG90Z1lQRVByWVY2ekw3RFUKLS0tIC9ONkRsQkczaHFtOVUrZ0RKYzUw
            RkVRVlZaY0lBNTF0cnRZRkl1UVVEeGMK3Miie5vcDIMrcUHxmKm+D5veouxYE0Cs
            6/T+0Zgb1pioSk8lTjaDZvw81EaqYxK9zQ07y0PG098OR1mNT0CnpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-23T09:19:39Z"
    mac: ENC[AES256_GCM,data:Bg2MFOW24k5mO987Sl53kcjWEuEIcifdjewidtVMOBoxA/G17OJqnySEmg33MuwROrtRqx6sM/MICEifrdfRTsBDDtJmREDqbB7sPnjk9Q3yAI8szKGPEGxkgtfY+MpxgggJtReSBqBXlOZPzuDtGpfKo3+RDbmNsyo7FWjOJvs=,iv:QJuFqr7tXVkApXi7jZ5A1Rwj4oK39lg0OJNZUQGW1Xw=,tag:vKf/maNAEvKNAUdUqAi/hw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
