apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:LfY3zXJDzeGTQX0yalh96OkYvQziwkE2R0IsY4WYibTJYKW4yyXTkAoOagghFG1oh9jPyO58zGvzG6KXp4/YOw5+iO2dTvRJiibJ27OSh+tOtAXFDI3X1tIeYbMwUFSTFAQ0vjwBoM/nlWD/sQfWMosTNMxxjbEyd/vvaV7cvqvW/R+dQWhvCBMmq9PVH9rNa+Yu/M2SpIWrtjB9vUJeGdWukD0OtEMpgwDXueojy4bLSqcK06rHpyDT3kibcJnNfTtWhtjG7zennVqfFYqTnoOX0po/NYY/OCgsRztzcNwE13mSqASMXwlw7F7oIII88iB+H7KZ54//kHX44TXsHrj8vu9ZtQDpG/YUNL/gXiYGewty9qrb6K8sMI/QeO2C,iv:1S4WlI7OLzM+C5CDg62pISKZwNswamPn9fzuCsBvoBs=,tag:dCl+kX4sukH2uDwPgVeOkQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:zedAB9uE7X5Z5pdJSM81ZcuoP2YSyGlw14tn33al+Pt6DaEsPs26hdYfsILS54nIQIeQbL+rrNBo+U+ONCxW/fcJ8YXoK7YuFhYC259SKQO6FKyC2Bh0R6V5OI/KLhFfDOtyYOcpYmzJwRCyzJ+wC5VHhx+/O0dRJ9/m31NNzBkf+ZNFrcWCXw//9f+GqT5w33fEhOzi2T/PEGFkjBTjgOUKAtnDh993VxLzF3CDuZPdH8QTPeXsseDU3pBSVMG/GM7IwW5gp+tnv87SWg==,iv:j5M8AEtYzdd+M78on5rbwMMct4AtdJkVeu/Jkh7R0pM=,tag:ZpBezOG3foe+/Jz83Iz0uw==,type:str]
    known_hosts: ENC[AES256_GCM,data:lDR1LJ2lPb1PQHY1QSdf+tkdChdpwBPQ3W5GwYYXhTWLMBeruLkpLAP6djKTmBLoK/S+CJpm9Xuai8wpPorLSnTZBROqWH2YXH/e6GKyB1XQ/+xMwmzpfnlrL8bR8DDCrryng8Yw5tUWUK++M44Rbsf++DBiv2Y+PlxiWShQ8PXkGyIxZ4GeDG8Z572j46QEXPey+H3Uem7daxZnGybHFQl+VsMFImLLnlJR,iv:3var5tmMruLwJ3E3AoY3U8s2k7c+Nx0CgIjJ4DNOVRE=,tag:GcVkeCqqEoxVN92a7Qjr8g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dpafzlyh6kar7u02x56k2g83tmg2g3t8aglwzupku8z639gqx5hsvts92d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUM3RMaHA1M0NkcVBuQ2dQ
            Z0tKT0RqTm5OTzhwZVhwTVFURG5sUmtNRHcwCmpYZ0x1RnFEeW10cEZlcXV5Y2du
            dVRSV3Rrb2hGc2hMYnh3V3loakhiMTQKLS0tIFdqYVVQZGlUOUdYMlE0VkRqSnJs
            VTY2QW83cHNpeVNJT3hkK001Wm4wa3cKb8T4EYU6KeJbrzPxJc3m6jyIedYH46z/
            Xgg41kf8/8t0iIFJE6aSwNE7KwOawdfsserTPv5cstt1zvf3Lvs/yQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T09:00:15Z"
    mac: ENC[AES256_GCM,data:ios72LiF/J8+ncO60L1jfKCC6AdQvE0n+KC03bQuyTdotDBz5mcPDzMp99mgYGFWSuaLOj7nXJZJld9OMcUSWhfHH1SRIM2N6pDzgeHF99c/EhCl64p3CTzoySTynPuF6v1OUi8C+MJQWdsCuxPz7SkOGwTf7tYWyMGQz1EZGAo=,iv:UurK5nlAd8O0z5/srl0BJUigiqeQ3OT+SSUMHT6xXnI=,tag:tzyP9Ro1+jFPhPa6RbLgDw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
