apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:peKAMvU1rSiiiycx5t3YgGS8Tp+EdlAfvidikpTaSOuXCsJG9PTedg3fUp7qP+/Tsw53K2leBp0gIzhiRwuMpWkF5TyEw51PN0NeZ1yNZBOmRyRR28HEQdO8ADhw+ZcL9F5ieDwFsXwYTRwa/WHeuisZkvNljO3FRkTbgwxxBH0V/lpj0bDUufK2DOperBgD3ZH4z7B8MnPWR8nin3xSUVLDieGIqZBfBn9luKp8/cm8+KW+5I0Y08p690Ke5g5E8jLUmWBNRKNg62loYl2WXBQOZK2Sy9a4qwSKwly4oUGUOg6VCD9hG4PaJDX5Qsebes2Dlih5aKv3DmBYYr4UJbYWe46i4gE2PWm7N5skRSLZN8ozww026tgJOSCocJZ9,iv:0AQwoen2X7U67X9dzhBhn9pLtdEsGDy8r58gtHhrfBc=,tag:Ts8DC/kCREaAlf27jXc3Wg==,type:str]
    identity.pub: ENC[AES256_GCM,data:xe/WSzxVKkQaEG9RvaU+zB4CvsNmDHFg43oWEVc6YeJ3gK5+5iEFgOBY07S5IDKe4tib7GH/JZ0apKQDmP0eZeB3WoqW90Y24hzinoONYGTG3VyK8pQRzLp97eRA2W+tphf3Gm68ubOPmd+dDKW7npR92B3G/r/Md+4El2561u9FK08hqURFB8X0EBNUHBFOvl4VqYW53tDXAVzhUpxJUMiwLlWysYwxlVihWr/B09roGDTY+BdmIJmk+DfqbWoTzhSDS1OzmBVLXCf0SQ==,iv:FR1CvIWLsojJ5pGbsmN/35hNriRbJfInZbIfjcBdUJw=,tag:jRZL/YkMKa1w+DPE1LzcgQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:r8lbMQKi3GPk0L/V71h38yk4uVyjFNm20xXZBsNWEF4JBNDRuPZUslzSe1LiNIWQ18t+5/8JaWq6mzxbPMmBcCIh0uPNXMMYgvWeuLE7NXcgpQCIaj7G1Ul6LhUVgtRgMLsZaYcMzFGNxQDJJbZm8OUyo7bmqL0C0cNnKClAvmh0BjSR/DkBnQQQepI+3gJDZLob6Pp0BoA6YPaodt/eNVu8qT7HlOTFeeBc,iv:bPSMguoT/6eLBGeIR2zzj24m80EMHMLQoO9QfXpC6T0=,tag:2VQ2/INy2vSRAuko/c9a6A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dpafzlyh6kar7u02x56k2g83tmg2g3t8aglwzupku8z639gqx5hsvts92d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCSVZuVDZWRktIQmJ5MWhX
            OWFvbHhyVkJGQzhtQkNJcFpFMzkzbGdmdGk4Cm51cEtwMlNnblZhTkJiVUxqRVll
            KzhQSnNoaXJMbnJiSmdsTDd1Y0JvYkEKLS0tIDZWRk1oWHo3emJ0S3o0L3VhUDFp
            OHMzTGc0WTRVWisyamVTQm40SDIrNzAKfMveaEgw/yMNjmXpY3/rVH2dPgLEILpH
            dDPLa3GjDkVNoL7ekBIxZvVrxlVl1p/yQENBvG1hmJIQLuQWA5lMVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T09:30:16Z"
    mac: ENC[AES256_GCM,data:tPEz2pxhRyMaL2PQqS8awsayqFZqjH5hqh8k8ruMEf4jVd1fCwsfWK5gBwDLnw8OXxpJELMjS+oPQZ6Zn+9MU54Y2trKugWzy9F+oELKHjjGYszHzQud89s20b+XxlaNX++CxZGEWE6ncD1rAk6FjAG5JiD4446P85bLHuuXvy8=,iv:EX4XMy5BFCfS35REHHj0i28yQi5/PbbNgmJybIamhWo=,tag:M9qtzMxVYOthvp0g25JLug==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
