apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-token
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:oF5+idJ6VPMKYaGrRmwRaDICo7ufvXLex82YlX+4UEdoWX28i64fgCQTrzlQEKOt6FnQj/1YdxzEyyg9e9ZZN9TikIeyLxNukCXsuYbv7zXVUhG+VYvvYFMkix2oXfhgxxecS6Y2xyruEulYR2XJXgUPRE3W5m6Kyvao0hySrqFJJ8KYPq9HQvhkw1BcalSDDp2g0CLza1+qgjBoQ5DVHXdYR9ZK+lvs1AwZv8aZ/iO60OVdcsp3,iv:dtKgcFEuQrtzBAnwi51m65FlIs3Bm7h3AL9bRlX4REc=,tag:T3yoBYv7KCZ4BphtCQJY6A==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dpafzlyh6kar7u02x56k2g83tmg2g3t8aglwzupku8z639gqx5hsvts92d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGa0lyUkFYQXYwTFRIdnhl
            dWM4VG5WS1gwWHZJQVd6c2llWUptVlNFcGg0CnVTRzVJcnhOb3lYMGpodWhmQmVR
            Y0Y4bUpaNmtMR3hRRTI1amJIV295YzQKLS0tIFBlS1lGbVhjck1QQ1pnbmNJQUo1
            WFRXSnVRZGtDM0kwc2hRbHVaT3B2TGMKNYabbj28SNQhuxqKZkPoPQBHD11W7jRo
            OUt8Pmi8nro72A3+1u7suQ7h6Ky20azj/hXvEOoJpeJE9vjQrNskGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-03T17:27:57Z"
    mac: ENC[AES256_GCM,data:MYHfqY0RtomI69bLGusoi3VGmhiNLuAVdbyMtmBRDDKkaT8KcEi1+j4K8wPBBpZEuHZtM+sxqsHJ5AR2m3zuwGpRPA9lDgv6+k/fMHn2Ltc6hNDQ8JbqBwpGRgvUVeI6SNiCuX5KgvfIEC0/cs9rSB5wwA1cZWmpGNWsX7Jl3is=,iv:5b/lnVWpdUwVDSwqHXPdTlVTZxdbU3FhkATkB23bO8s=,tag:IWUVdM7C0SGqXJglcUWGsQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
