apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-token
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:SpZY0XykAcGlBMRL/g0/oVSjEdRVeyXzmFjpEHHXt26GnV+1TjItN18e+zK6tAOkJ84tfo1kkR3ctDozabVpxMF8zvLSi6IP2iYC4FJPuqLOHYkrLaTZS/HPJ/Hrbt5rMxGq40Yn88YFFxPOX7UX2oekY7qcuNxiBKjPKrGWsbiNQwYjQ1KyBw3gLFrnEb//bgsCFfg6F3q8LIo3lYJo7yktU+PJx7XoHW+bUrG7wbqeUIXatTlq,iv:4yjtpOAkpDytc9pEpvJS7Sdp9YiYTDeSchyZzRRK9LU=,tag:Ek5Un8nkXhILT+PBLuQ7/g==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dpafzlyh6kar7u02x56k2g83tmg2g3t8aglwzupku8z639gqx5hsvts92d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5TXl3TXQ5QWY5SmI0dnBG
            QmFkdldXWXpIcWp6K09yYWRWZFNuYnlvN2dVCjlRUVZmelBudnU3SndMZXk1dlhm
            SkJQdFFlODdaZ0tRUVd1M1NpNW5VRFkKLS0tIGxqbGNRekJoa25VWWtFbEhNaklt
            dnMyZ21ubG9OSmphZXBlcDNJVkJwT2MK6jAtIOwC/ALW98qVHLC41/Q72MFCKzsK
            oCmdE1okENoX67QJx+Q2okfdVOa1f9A+BhRbqCKHxVGCamDUD81JdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-03T05:49:06Z"
    mac: ENC[AES256_GCM,data:vJxPFq4sJpNZdhyFrdhPziM1g/pnDDzx5pt5WS3TWnrI3adbA/c5WNX1PHoEFdFAjQVYL8PLUj27u60mU67QmeqRAMVkeHg8D3Pj+AkWXW2SU4+34QgLUkMQWBSjmQKQoYnVGC/N3HMm6CjGjvD4ix+BrTxTu0p8EB3iRaZEKR4=,iv:NqYJsifQad293gJahrn52FAdCWc/H2I8NTol2TpZQRI=,tag:nzH9joE+x8PsAr9HvuDj/g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
