apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-token
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:Cz+HdK8Z2wgfs7vgxZEdxl45qUjE9uTRp/fwTaOAdj0ZEtjiC6unyNgEmcOyE1smfY1iQPJdYXe5Vkjbx+seULpahkGsFEPf+H+Nzsd/WGdZBJQovggCZu49RnAOlSV0eXwuTLUZp75x1TD03o8FkwDBZs20n4IeFfEOPK3skEAK46U/kCu0b0FKwvUcrJ2uK52SxsH/UnDV5zIHrqeZBi5JCmPswwhV65FFxvlq1BLqJG7b58So,iv:0IuOjcSJqCvo1/CQrTojRzxM7djqUeFHueHmLJUKruE=,tag:q03SLOf02d/EO3fkLmCaBA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dpafzlyh6kar7u02x56k2g83tmg2g3t8aglwzupku8z639gqx5hsvts92d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQT3hJSzNvaGJmaVZCRWJ2
            dTUvU1BIa3QrdGxsc2o2U2ZvaXY4NStLT1ZnCk5vVG9xU2NNV0YxT3RzMFVyRGVV
            bTV0b0M2M0JRNVFsZVA0ZUxRWC9wbjAKLS0tIGFiWHEyZ1IyWjBGT2tHeUVsWjJx
            RWk1Y1JGUjA4OTFSc256S003ZG1YZWcKe6MRdDmcFUy0Oxazrd+ioaWpRGDFn69j
            VjaKNv1g2jx0FdFCMhur2nD2mdB9ZwoeYbXtGK6Z8/yjpZ5PL2CTFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-19T04:32:36Z"
    mac: ENC[AES256_GCM,data:8oQ/H54CjxQai4XGeJ6qtmZd8PxzlJbaehRnO5ElDRd6eHGcuu8a/ddXzVU9WhkhPLQJHsC6Vv4kkhnPt0mJqTVopwti0QNMNas1k0t6wmbMExr8hpEKoI3/idohvNxqXVRpFMagI8uWf2byWr9xqIyhdrD8t6Z1T0BEgXUO6fY=,iv:PcloYuIzcHb6+B3xoRtlx5xdr5f88LV64rk0QF1bp6w=,tag:neC2DBvwXse6zdoncul/8g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
