apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-token
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:rxsv64+UiaxB18HO19Apyfw3L/gS0HCjR1hjIdYrEnG5FzMa3e9mTAlT4FJ0H2X6qFOR71rq5saamzD545XWuu2WA631lLDahg4461VffeY7P8X9x+cGnlzPq7+BQn3g5IPWcqsvbrC0ZJOmL3uA5HpbcNx1W8HwK9jFzbhb6TFxrFg1UBs6qUMbN5k9vQUHuX61EQXHGtV5PaZWBpNi47vOPoTZR6j1FPbtb57YFFstXgHW+F6u,iv:VLDmBtcWU50iV+tqFXqfwv7z0VBcvaGx83jDYrxbZS4=,tag:suypShvQ5UGsxK2jw45HoQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dpafzlyh6kar7u02x56k2g83tmg2g3t8aglwzupku8z639gqx5hsvts92d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXRXROMHJsdmNEenE5VFFU
            K3cvTERCMjVmcG5XZmdzNUhJY2xpVjc3ZGp3CnRIZXIrMkc2V2pxSkJzczZralI3
            Z0QyZ0t5bUFIQnpmekxwam1nYjY3blkKLS0tIE4yVE50S1lqQnZmTEFMdGp6cklM
            Y3Q5eWxnYWRRa3VjaVFJNEdTM3NCTG8KrWK3JvuupyjOUOUG281fH6e7QJtAPZMg
            JGRZL6q3sKuCmPVL8fgbF4CRWYt0DPJrghMdCYtQQ/E0hGRRxmv+Pg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-03T19:02:51Z"
    mac: ENC[AES256_GCM,data:CG0eydxdZdynFawLk8Vpt0jcYI8F+NWKsxKEe2fU4cZ4AkCm/ZUF3XcJP6tTX+A0JTzfqPGoBFqBQOX2oqakMZQET++KydecG09umjzgf2BHzjYhcyZ2SMINw4ctjdo4cclmNsegloigwpU/HZQJmrm/PoeKDaCLFEwkMr40rN8=,iv:DqyAe1je1VtvmsPbMb9Q44HBz9iMP16XHTsGfUe/Lzc=,tag:uR7pVXFwufjWAABmBdq1yg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
