apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-token
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:Jk7w6/CqDfvx22MNbxzEGEnZZLTjYLbvc9juWqCKxFU40HrwhDzyjGJpM6rUcV6E2NnDOP01HMrqPxpVYf84M0ENe52OK+Gmqip5+cIxNx2RBsNFW/iXW/2wKJS7DFNmzgH+xoLZasieL7ZsB4SC/63fX3gZ6ra8pLU+KUkAwjv+5uUEEZxWi1s2fGqN8eYs4f5U0udwa2bvelBXNW8g62ZSKJBzrXaL5reK9wdo3gcW+A1DWVLx,iv:GYkZ4XkVoIoisXHYszZtxAsOS2ASqN0Pb2dk1kuB9bY=,tag:H4q4zcNvLr8Pnai0SyOOFg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dpafzlyh6kar7u02x56k2g83tmg2g3t8aglwzupku8z639gqx5hsvts92d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6SXpLcHRsV0VYWXA1ZVRE
            YUFtWTduU1c3azR2VnNPdm8wN1Y4d3FZZFE0CjduT3VTR0hGb2FjNGtQNldERDZq
            UjIwM1NVY08remVYRi9xZURnQ24wUWsKLS0tIElmZjFUZGh0cE0zaEFvVUYralNN
            ZXdWbVZQN3dGTi9yV0IzU0RkZWcyYVkK3GOkVGuIWN3VNVyKuRdtF9eNiE7XowqX
            0/F5De/0waIYQANuRh316dZxEhpgY4h8t6FeDXUxu2WnM55c+mdENA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-05T10:18:05Z"
    mac: ENC[AES256_GCM,data:BzNphoICbvsGHBS82Qc6d8AsP/X3LTPzhP/CcR1BxMiJtPNixgjDpHkNs1BIbd4H5Ye+vbPIlXsCHyEYE0EqKIBvjgDSlCH30w5y7/8TYTVysMKTDVNvBYWBE48snUdc69VtQVbAftPNPC6bDMCHYVFSN2+jjgt88HeOdb33bs8=,iv:99x8EoGBQSWeFfo+Juyl5LtdiR+Mua2oxgldgggU7gg=,tag:JRUi7qF/JYFeAg9xWTPCCQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
