apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bazarr/ks.yaml
  - flaresolverr/ks.yaml
  - jellyfin/ks.yaml
  - jellyseerr/ks.yaml
  - jellystat/ks.yaml
  - lidarr/ks.yaml
  - notifiarr/ks.yaml
  - prowlarr/ks.yaml
  - qbittorrent/ks.yaml
  - radarr/ks.yaml
  - sonarr/ks.yaml
  - sonarr-anime/ks.yaml
  - unpackerr/ks.yaml
  - metube/ks.yaml
