apiVersion: v1
kind: Secret
metadata:
    name: authelia-oidc-secret
    namespace: authelia
type: Opaque
stringData: null
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dpafzlyh6kar7u02x56k2g83tmg2g3t8aglwzupku8z639gqx5hsvts92d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBbGtZZGdEQVNZaVA4Ylpv
            UlJmbnExR0p0QXR1TU4yeTJXUHh2V3Y4YkRrCjloUFQ2L2c5OUU3Z2VTV1RKNVNi
            eXV3M051NmNTNGpRZDcyS2s2OWdlZDQKLS0tIHpxbEN1SXdrWVk4dGZoaWxUVG05
            eGlQWWdPNVVEbGVxemY5cXFraklId2sKylZ0ettHiEnYIvQm+6OdIGDi8nDv/R2m
            xgH2005yqaPMQ781SRgXrNTS+E36EO8nfYmkUyYg5Z9A+tUhirICMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-19T04:32:36Z"
    mac: ENC[AES256_GCM,data:AP4LSfVic+IBZqJR2D61gpb898JWFpQo+r3pD9a7R4KUBVh/z+kp0R6EX4DMz9BcdntPFEsm3EP8Mv4Y28ZzVTaJS5LZv8RMEjT+rHXrKm4RL41OoBpWyWwFfQjD4u+Vn/MS9Iqt9bmmza1p3cxEC8IY8L/YMLqtQ8FoDlTW6Zc=,iv:uvsJymFWDW9QTti1KzjA0+N9lhPG2McHrPiyjyK8tw4=,tag:thnx3zfsMwEVb3yISlYVlg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
