apiVersion: v1
kind: Secret
metadata:
    name: authelia-oidc-secret
    namespace: authelia
type: Opaque
stringData: null
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dpafzlyh6kar7u02x56k2g83tmg2g3t8aglwzupku8z639gqx5hsvts92d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHTHFBQmg1N3M3d0NReHFm
            OU83VW42YVArNGVSUExyNkoyRnVVc1BWVEE4Ci9jaEVzbExPYlkzTG9HdllhMm1J
            Y3pSaE9hYWczRm9LSFdWc3NrUEVMTVEKLS0tIEVuZU9zeFROOHE2anY1U3lma2oy
            dnBQZlBiWHpnRFdZWEhiUStwVzhkTFEKbZZWz4/msqRJA0csIfggCQa7EEV1A505
            NSj+PUm5DYy4H8FxBDPa0JVKcqnqv2CD9uHJXjKbmQyigEsHLgcgAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-08T21:31:45Z"
    mac: ENC[AES256_GCM,data:HJTrsbyxXkKqPQBh1PJ4WTZ0LO42vVaeiNjmg7ZA1x1PSMOXP7o9A6g7JWTaS1b4jATVSVyvR1j6HJRBLof7t8kiVjkj68wQxsC9nBhY0/znVAwAvSmaQbC6N50DS6WTSbkzaQ2eK5eingMJ3r2do9OMeJy4L4450oMexyBntwc=,iv:pxA3ZrLf40JVChoD1oeI1ce9XLxv9VNQvvTFxMa13ro=,tag:5EbuxhOz8vrHVhY68VuYyg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
