apiVersion: v1
kind: Secret
metadata:
    name: authelia-oidc-secret
    namespace: authelia
type: Opaque
stringData: null
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dpafzlyh6kar7u02x56k2g83tmg2g3t8aglwzupku8z639gqx5hsvts92d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuNlVVcGdmNnBzUzJIL1R5
            SU9SKzNMdXR0d3ZlZmJPQnVaZDZXUjc3MUVBCml6eForVUFxT2RBUVoweWJLZzd4
            VTZzbEdwNDlCalpxZXZ6bElzb1hPb0kKLS0tIGZseFhyVWJJcnpybGxqVVZKL2FT
            OE1hUUtuc1V3bGw3OTN0a2FPQmRCWGcKK+2K7WHLm5Xw/TkaMwar/M4jSvqsPfVg
            aailJXYmBfOyMy/OnQxpFCTHzwkG18MlJ+8hzmw10i89o7MSlV+QuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-03T17:27:56Z"
    mac: ENC[AES256_GCM,data:jhONqggibjYtnbbhf8omWv1pyNWK5TuYUCbHwSeSalOux3T7WbgktnulZ1A1NhjfDtkgusTLrYPItjdeEmJOxWLAWTThfLB4fSB6QO7j7kjR9N0HePmIqnhhtASOX8dD3TQPa5fqoQJLqmGgvp9ZvAyZk74fi8jzv4nQYj+NY0U=,iv:sxOsescfrJxv4WZVFBDqkBi7LX2b/MfyrSxClEUtM80=,tag:qKoAaZhwxXlViEQtg8bLoA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
