apiVersion: v1
kind: Secret
metadata:
    name: authelia-oidc-secret
    namespace: authelia
type: Opaque
stringData: null
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dpafzlyh6kar7u02x56k2g83tmg2g3t8aglwzupku8z639gqx5hsvts92d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGOTdxS25mOFpIMkhXbE1x
            U0xqWk0xcXVVcWdZZEpVT2RNU3pCY1lYdmtnCk93eDFZQ3RiK29veDJMcUN2aC9C
            Z21VR2pVR1ZCdEJIQzhmUEc0UjhibFEKLS0tIGFoZFRhUGx3WWc3UlFVV1Zna2xX
            dkd1NTF2VEJ0WVlCdE9MTkJBc0hBQzgKXvp0SGQVeWT+9YfVJRECBKClwq2prOmH
            edWFWCWOAUeEecTrZHKMZWaPgKeR0498fWoL/fRC1/VdbPMPmtfHYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-03T05:49:06Z"
    mac: ENC[AES256_GCM,data:C4Xmr8m7Ymer4qPIhyBRAu//WQIHL/TDQ9ukX5yUiHhB+etJrO5trJ1hvAWpMAkIKgp4wiPgtQEXQfXhlEjOe584PQCg6ISL1FTVBBQAjwkWDlPXVsRnpJok8FfghLx1icf8dlz+Jgd5N7q8rHzQjMWdDBWuueIAanjPnRcBWgQ=,iv:rv3fssykdsqtcC+7opfbMZDEogfzFIbj4Cd0F1ZNHhI=,tag:yuDjRJZXXmoX96tfq05d2g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
