apiVersion: v1
kind: Secret
metadata:
    name: authelia-oidc-secret
    namespace: authelia
type: Opaque
stringData: null
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dpafzlyh6kar7u02x56k2g83tmg2g3t8aglwzupku8z639gqx5hsvts92d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2T1R5WDdYMFRRZVg5SDFY
            cTNpQnA4b0ZQODVkYjQwNmZrZU9xalhFWXhRCk9WV2F0YW1nTnoySEhDaWRaQnc2
            OFhsRkJLSENIY3lkSU5zamFJRGxQeVkKLS0tIDR3NDAzVThDcVNGK2IyRFM0NkVm
            MFEva2lic0xJY1JGamM5VFZWemlkY3cKDbquegtihM9Lfz+itNHMS/vBjFvCgFu3
            rLi3lf/uYRNcpE5k5jjuKtaZA23jGT7zH5GsFvjiKLsfwLtCMkP/uw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-03T19:02:51Z"
    mac: ENC[AES256_GCM,data:7V0XaK0nGrLYU7LApkJkd4TeHEtCP90t/xadO+I0J68ts9NdHDdDlGr2tlXQTa1xuphV1/Rciiu3pqrdkjjwm7IwkwQM/Sj21PBz0zer4p3a215kp7eqjlz2YS/rdPJzFtteYjMLQkXtLX22DuvNtsg53czAr+9eZ4/Upj+9Tk8=,iv:xxIJODdXIgQzimGBRv9k4jyIAivvppZybkXfxwwk4iA=,tag:JIyANSFchyhjk/cdOtz1iA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
