---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: clusterissuer
  namespace: clusterissuer
spec:
  interval: 15m
  chart:
    spec:
      chart: clusterissuer
      version: 10.13.18
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:

    TZ: ${TIMEZONE}

    clusterIssuer:
      ACME:

        ## DOMAIN_0
        - name: domain-0-le-staging
          email: "${DOMAIN_0_EMAIL}"
          server: 'https://acme-staging-v02.api.letsencrypt.org/directory'
          type: "cloudflare"
          cfapitoken: "${DOMAIN_0_CLOUDFLARE_TOKEN}"
        - name: domain-0-le-prod
          email: "${DOMAIN_0_EMAIL}"
          server: 'https://acme-v02.api.letsencrypt.org/directory'
          type: "cloudflare"
          cfapitoken: "${DOMAIN_0_CLOUDFLARE_TOKEN}"

        ## DOMAIN_1
        - name: domain-1-le-staging
          email: "${DOMAIN_1_EMAIL}"
          server: 'https://acme-staging-v02.api.letsencrypt.org/directory'
          type: "cloudflare"
          cfapitoken: "${DOMAIN_1_CLOUDFLARE_TOKEN}"
        - name: domain-1-le-prod
          email: "${DOMAIN_1_EMAIL}"
          server: 'https://acme-v02.api.letsencrypt.org/directory'
          type: "cloudflare"
          cfapitoken: "${DOMAIN_1_CLOUDFLARE_TOKEN}"

    clusterCertificates:
      # Namespaces in which the certificates must be available
      # Accepts comma-separated regex expressions
      replicationNamespaces: '.*'
      certificates:
        - name: domain-0-wildcard
          enabled: true
          certificateIssuer: domain-0-le-prod
          hosts:
            - ${DOMAIN_0}
            - '*.${DOMAIN_0}'
        - name: domain-1-wildcard
          enabled: true
          certificateIssuer: domain-1-le-prod
          hosts:
            - ${DOMAIN_1}
            - '*.${DOMAIN_1}'
