apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tuppr
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/system/system-upgrade/tuppr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster

